import type { Category, Product, ProductType } from "./types";


/**
 * Product catalog — the inventory defined in Step 2.
 * Actual files (docx/pdf/epub/zip/covers) are generated by
 * `npm run content:generate` into /storage and referenced here.
 */
export const PRODUCTS: Product[] = [
  // ================= PROMPT PACKS =================
  {
    id: "pkg-fre-01",
    sku: "PKG-FRE-01",
    title: "Freelance Client Machine: Outreach & Proposals",
    description:
      "15 copy-paste prompts for cold outreach, proposals, discovery calls and follow-ups that don't sound like AI.",
    productType: "prompt",
    category: "freelance",
    priceGhs: 75,
    promptCount: 10,
    formats: ["pdf", "docx"],
    filePaths: {
      pdf: "storage/prompts/pkg-fre-01/pack.pdf",
      docx: "storage/prompts/pkg-fre-01/pack.docx",
    },
    samplePath: "storage/prompts/pkg-fre-01/sample.txt",
    active: true,
    featured: true,
    createdAt: "2026-08-20T00:00:00.000Z",
  },
  {
    id: "pkg-fre-02",
    sku: "PKG-FRE-02",
    title: "Freelance Client Machine: Money, Scope & Hard Conversations",
    description:
      "15 prompts for rate negotiations, scope-creep replies, invoice chasing and saying no — firm, never rude.",
    productType: "prompt",
    category: "freelance",
    priceGhs: 85,
    promptCount: 10,
    formats: ["pdf", "docx"],
    filePaths: {
      pdf: "storage/prompts/pkg-fre-02/pack.pdf",
      docx: "storage/prompts/pkg-fre-02/pack.docx",
    },
    samplePath: "storage/prompts/pkg-fre-02/sample.txt",
    active: true,
    createdAt: "2026-08-20T00:00:00.000Z",
  },
  {
    id: "pkg-fre-03",
    sku: "PKG-FRE-03",
    title: "Freelance Business Engine (Full System)",
    description:
      "The complete 40-prompt system: outreach, proposal, pricing, delivery, testimonial and retention with a weekly AI routine.",
    productType: "prompt",
    category: "freelance",
    priceGhs: 145,
    promptCount: 8,
    formats: ["pdf", "docx"],
    filePaths: {
      pdf: "storage/prompts/pkg-fre-03/pack.pdf",
      docx: "storage/prompts/pkg-fre-03/pack.docx",
    },
    samplePath: "storage/prompts/pkg-fre-03/sample.txt",
    active: true,
    createdAt: "2026-08-20T00:00:00.000Z",
  },
  {
    id: "pkg-mkt-01",
    sku: "PKG-MKT-01",
    title: "Copy That Converts: Ads & Emails",
    description:
      "15 prompts for ad headlines, hooks, sales emails and landing-page copy built on proven direct-response patterns.",
    productType: "prompt",
    category: "marketing",
    priceGhs: 85,
    promptCount: 10,
    formats: ["pdf", "docx"],
    filePaths: {
      pdf: "storage/prompts/pkg-mkt-01/pack.pdf",
      docx: "storage/prompts/pkg-mkt-01/pack.docx",
    },
    samplePath: "storage/prompts/pkg-mkt-01/sample.txt",
    active: true,
    featured: true,
    createdAt: "2026-08-20T00:00:00.000Z",
  },
  {
    id: "pkg-mkt-02",
    sku: "PKG-MKT-02",
    title: "Copy That Converts: Content, Social & SEO",
    description:
      "15 prompts for blog structures, social captions, SEO briefs and content calendars that keep one consistent voice.",
    productType: "prompt",
    category: "marketing",
    priceGhs: 85,
    promptCount: 10,
    formats: ["pdf", "docx"],
    filePaths: {
      pdf: "storage/prompts/pkg-mkt-02/pack.pdf",
      docx: "storage/prompts/pkg-mkt-02/pack.docx",
    },
    samplePath: "storage/prompts/pkg-mkt-02/sample.txt",
    active: true,
    createdAt: "2026-08-20T00:00:00.000Z",
  },
  {
    id: "pkg-smb-01",
    sku: "PKG-SMB-01",
    title: "SMB Operator: Marketing, Reviews & Local Growth",
    description:
      "15 prompts for social posts, Google reviews, local ads and customer win-back messages for busy owners.",
    productType: "prompt",
    category: "smb",
    priceGhs: 85,
    promptCount: 10,
    formats: ["pdf", "docx"],
    filePaths: {
      pdf: "storage/prompts/pkg-smb-01/pack.pdf",
      docx: "storage/prompts/pkg-smb-01/pack.docx",
    },
    samplePath: "storage/prompts/pkg-smb-01/sample.txt",
    active: true,
    createdAt: "2026-08-20T00:00:00.000Z",
  },
  {
    id: "pkg-cre-01",
    sku: "PKG-CRE-01",
    title: "Creator Script System: Hooks & Long-Form",
    description:
      "12 prompts for retention-structured hooks, beat sheets and 8–12 minute scripts with anti-generic constraints.",
    productType: "prompt",
    category: "creators",
    priceGhs: 75,
    promptCount: 8,
    formats: ["pdf", "docx"],
    filePaths: {
      pdf: "storage/prompts/pkg-cre-01/pack.pdf",
      docx: "storage/prompts/pkg-cre-01/pack.docx",
    },
    samplePath: "storage/prompts/pkg-cre-01/sample.txt",
    active: true,
    createdAt: "2026-08-20T00:00:00.000Z",
  },
  {
    id: "pkg-dev-01",
    sku: "PKG-DEV-01",
    title: "AI Pair Programmer: Code, Debug & Review",
    description:
      "20 prompts for generating, debugging and reviewing code with context-stuffing and test-first instructions.",
    productType: "prompt",
    category: "dev",
    priceGhs: 145,
    promptCount: 10,
    formats: ["pdf", "docx"],
    filePaths: {
      pdf: "storage/prompts/pkg-dev-01/pack.pdf",
      docx: "storage/prompts/pkg-dev-01/pack.docx",
    },
    samplePath: "storage/prompts/pkg-dev-01/sample.txt",
    active: true,
    createdAt: "2026-08-20T00:00:00.000Z",
  },

  // ================= EBOOKS =================
  {
    id: "ebk-fre-01",
    sku: "EBK-FRE-01",
    title: "The Freelancer's AI Client Machine",
    description:
      "The complete method for winning clients and handling money talks with AI — proposals, scope, rates and follow-ups that close.",
    productType: "ebook",
    category: "freelance",
    priceGhs: 175,
    pageCount: 40,
    author: "Obed Cudjoe",
    toc: [
      { title: "Why Your AI Proposals Fail (and the 4-line fix)", pages: 5 },
      { title: "The Client Machine Method: Context → Constraint → Voice", pages: 8 },
      { title: "Outreach & Proposals That Win", pages: 7 },
      { title: "Money Talks: Scope, Rates & Difficult Conversations", pages: 7 },
      { title: "The Prompt Workbench: 15 Core Prompts, Explained", pages: 8 },
      { title: "The 7-Day Implementation Plan", pages: 5 },
    ],
    formats: ["pdf", "epub"],
    filePaths: {
      pdf: "storage/ebooks/ebk-fre-01/book.pdf",
      epub: "storage/ebooks/ebk-fre-01/book.epub",
    },
    coverPath: "storage/ebooks/ebk-fre-01/cover.jpg",
    samplePath: "storage/ebooks/ebk-fre-01/chapter1.pdf",
    active: true,
    featured: true,
    createdAt: "2026-08-20T00:00:00.000Z",
  },
  {
    id: "ebk-mkt-01",
    sku: "EBK-MKT-01",
    title: "Human-Sounding AI Copy",
    description:
      "How to make AI write copy that doesn't scream ChatGPT — voice briefs, de-AI editing and prompt patterns for ads, emails and landing pages.",
    productType: "ebook",
    category: "marketing",
    priceGhs: 185,
    pageCount: 36,
    author: "Obed Cudjoe",
    toc: [
      { title: "The AI Tell: Why Everyone Recognizes ChatGPT Copy", pages: 6 },
      { title: "The Voice Brief: Teaching AI Your Brand Voice in 10 Minutes", pages: 8 },
      { title: "The De-AI Editing Pass: 3 Rounds to Human", pages: 8 },
      { title: "Prompt Patterns for Ads, Emails & Landing Pages", pages: 8 },
      { title: "Your Voice Library: Checklists & 30-Day Plan", pages: 6 },
    ],
    formats: ["pdf", "epub"],
    filePaths: {
      pdf: "storage/ebooks/ebk-mkt-01/book.pdf",
      epub: "storage/ebooks/ebk-mkt-01/book.epub",
    },
    coverPath: "storage/ebooks/ebk-mkt-01/cover.jpg",
    samplePath: "storage/ebooks/ebk-mkt-01/chapter1.pdf",
    active: true,
    createdAt: "2026-08-20T00:00:00.000Z",
  },
  {
    id: "ebk-smb-01",
    sku: "EBK-SMB-01",
    title: "The Small Business AI Playbook",
    description:
      "A 2-hour setup plus a 30-minute weekly routine that lets AI handle marketing, reviews, customer service and admin.",
    productType: "ebook",
    category: "smb",
    priceGhs: 175,
    pageCount: 44,
    author: "Obed Cudjoe",
    toc: [
      { title: "The 2-Hour AI Setup for Busy Owners", pages: 6 },
      { title: "Marketing That Runs Itself (Social, Ads, Reviews)", pages: 8 },
      { title: "Customer Service Without Hiring", pages: 7 },
      { title: "Ops & Admin: SOPs, Invoices, Scheduling", pages: 7 },
      { title: "The SMB Prompt Library: 15 Core Prompts", pages: 9 },
      { title: "Your Weekly 30-Minute AI Routine", pages: 7 },
    ],
    formats: ["pdf", "epub"],
    filePaths: {
      pdf: "storage/ebooks/ebk-smb-01/book.pdf",
      epub: "storage/ebooks/ebk-smb-01/book.epub",
    },
    coverPath: "storage/ebooks/ebk-smb-01/cover.jpg",
    samplePath: "storage/ebooks/ebk-smb-01/chapter1.pdf",
    active: true,
    createdAt: "2026-08-20T00:00:00.000Z",
  },

  // ================= BUNDLES =================
  {
    id: "bnd-mkt-01",
    sku: "BND-MKT-01",
    title: "Complete Marketing AI Toolkit",
    description:
      "Everything marketers need: the 45-prompt copy & content system, the social/SEO pack and the Human-Sounding AI Copy ebook — one ZIP, 27% off.",
    productType: "bundle",
    category: "marketing",
    priceGhs: 319,
    items: [
      { productId: "pkg-mkt-03", position: 0 },
      { productId: "pkg-mkt-02", position: 1 },
      { productId: "ebk-mkt-01", position: 2 },
    ],
    formats: ["zip"],
    filePaths: { zip: "storage/bundles/bnd-mkt-01/bundle.zip" },
    active: true,
    featured: true,
    createdAt: "2026-08-20T00:00:00.000Z",
  },
  {
    id: "bnd-fre-01",
    sku: "BND-FRE-01",
    title: "Freelance Growth Bundle",
    description:
      "The 40-prompt Freelance Business Engine, the outreach pack and the Freelancer's AI Client Machine ebook — one ZIP, 27% off.",
    productType: "bundle",
    category: "freelance",
    priceGhs: 289,
    items: [
      { productId: "pkg-fre-03", position: 0 },
      { productId: "pkg-fre-01", position: 1 },
      { productId: "ebk-fre-01", position: 2 },
    ],
    formats: ["zip"],
    filePaths: { zip: "storage/bundles/bnd-fre-01/bundle.zip" },
    active: true,
    createdAt: "2026-08-20T00:00:00.000Z",
  },
  {
    id: "bnd-cre-01",
    sku: "BND-CRE-01",
    title: "Creator Launch Bundle",
    description:
      "The 35-prompt Creator Complete System, the Shorts/Titles pack and the Creator Script System ebook — one ZIP, 26% off.",
    productType: "bundle",
    category: "creators",
    priceGhs: 299,
    items: [
      { productId: "pkg-cre-03", position: 0 },
      { productId: "pkg-cre-02", position: 1 },
      { productId: "ebk-cre-01", position: 2 },
    ],
    formats: ["zip"],
    filePaths: { zip: "storage/bundles/bnd-cre-01/bundle.zip" },
    active: true,
    createdAt: "2026-08-20T00:00:00.000Z",
  },
];

/** Placeholder packs referenced by bundles — filled in by content generation. */
export const PLACEHOLDER_PRODUCTS: Product[] = [
  {
    id: "pkg-mkt-03",
    sku: "PKG-MKT-03",
    title: "Complete Copy & Content System",
    description:
      "The full 45-prompt marketing system: positioning, campaigns, copy, content, repurposing and performance review.",
    productType: "prompt",
    category: "marketing",
    priceGhs: 165,
    promptCount: 8,
    formats: ["pdf", "docx"],
    filePaths: {
      pdf: "storage/prompts/pkg-mkt-03/pack.pdf",
      docx: "storage/prompts/pkg-mkt-03/pack.docx",
    },
    active: true,
    createdAt: "2026-08-20T00:00:00.000Z",
  },
  {
    id: "pkg-cre-02",
    sku: "PKG-CRE-02",
    title: "Creator Script System: Shorts, Titles & Thumbnails",
    description:
      "15 prompts for Shorts scripts, CTR titles, thumbnail concepts and packaging that stops the scroll.",
    productType: "prompt",
    category: "creators",
    priceGhs: 85,
    promptCount: 10,
    formats: ["pdf", "docx"],
    filePaths: {
      pdf: "storage/prompts/pkg-cre-02/pack.pdf",
      docx: "storage/prompts/pkg-cre-02/pack.docx",
    },
    active: true,
    createdAt: "2026-08-20T00:00:00.000Z",
  },
  {
    id: "pkg-cre-03",
    sku: "PKG-CRE-03",
    title: "Creator Complete System",
    description:
      "The full 35-prompt system: ideas, research, scripts, packaging, repurposing and analytics.",
    productType: "prompt",
    category: "creators",
    priceGhs: 155,
    promptCount: 8,
    formats: ["pdf", "docx"],
    filePaths: {
      pdf: "storage/prompts/pkg-cre-03/pack.pdf",
      docx: "storage/prompts/pkg-cre-03/pack.docx",
    },
    active: true,
    createdAt: "2026-08-20T00:00:00.000Z",
  },
  {
    id: "ebk-cre-01",
    sku: "EBK-CRE-01",
    title: "The Creator Script System",
    description:
      "A retention-first scripting framework — hooks, beat sheets, Shorts, titles and thumbnails.",
    productType: "ebook",
    category: "creators",
    priceGhs: 165,
    pageCount: 40,
    author: "Obed Cudjoe",
    toc: [
      { title: "Why Generic Scripts Die in the First 15 Seconds", pages: 5 },
      { title: "The Retention Map: Hooks, Loops & Payoffs", pages: 8 },
      { title: "Long-Form Scripting That Sounds Like You", pages: 7 },
      { title: "Shorts, Titles & Thumbnails", pages: 8 },
      { title: "The Creator Prompt Workbench", pages: 7 },
      { title: "From Script to Upload: Your Weekly System", pages: 5 },
    ],
    formats: ["pdf", "epub"],
    filePaths: {
      pdf: "storage/ebooks/ebk-cre-01/book.pdf",
      epub: "storage/ebooks/ebk-cre-01/book.epub",
    },
    active: true,
    createdAt: "2026-08-20T00:00:00.000Z",
  },
];

const ALL: Product[] = [...PRODUCTS, ...PLACEHOLDER_PRODUCTS];
export const FREE_ITEMS = [
  {
    id: "free-prompts",
    title: "5 Free Freelance Prompts That Actually Work",
    description:
      "Full-quality prompts for outreach, proposals, scope creep, invoice chasing and testimonials — the same standard as our paid packs.",
    filePaths: {
      pdf: "storage/samples/free-prompts.pdf",
      docx: "storage/samples/free-prompts.docx",
    },
  },
  {
    id: "free-chapter",
    title: "Free Chapter — Why Your AI Proposals Fail",
    description:
      "Chapter 1 of The Freelancer's AI Client Machine, plus the 12-page Prompt Recipe mini-guide.",
    filePaths: {
      pdf: "storage/samples/free-chapter.pdf",
    },
  },
];

export const baseAll: Product[] = [...PRODUCTS, ...PLACEHOLDER_PRODUCTS];
