# Real ebook content — used by scripts/generate_content.py
# Each ebook: metadata + chapters with paragraphs. PDF/EPUB built by generator.

EBOOKS = [
    {
        "id": "ebk-fre-01",
        "sku": "EBK-FRE-01",
        "title": "The Freelancer's AI Client Machine",
        "subtitle": "Proposals, outreach and money talks that close",
        "author": "Obed Cudjoe",
        "desc": "The complete method for winning clients and handling money talks with AI - proposals, scope, rates and follow-ups that close.",
        "category": "freelance",
        "price": 175,
        "pages": 40,
        "toc": [
            "Why Your AI Proposals Fail (and the 4-line fix)",
            "The Client Machine Method: Context → Constraint → Voice",
            "Outreach & Proposals That Win",
            "Money Talks: Scope, Rates & Difficult Conversations",
            "The Prompt Workbench: 15 Core Prompts, Explained",
            "The 7-Day Implementation Plan",
        ],
        "blurb": "A working freelance method, not a theory book. Every chapter ends with Action Steps you can do today.",
        "chapters": [
            {
                "title": "Why Your AI Proposals Fail (and the 4-line fix)",
                "paras": [
                    "Every freelancer has had the same experience. You paste a client's brief into ChatGPT, ask for a proposal, and get back something that sounds like a marketing agency wrote it - for a different company. The client reads it, feels nothing, and hires someone else. You blame the AI. The AI wasn't the problem.",
                    "The problem is that most freelancers prompt like they're ordering food. 'Write me a proposal' is the equivalent of walking into a restaurant and saying 'give me food'. You'll get something edible. You won't get something you'd pay for.",
                    "Here is the four-line fix that changes everything. Before you ask the AI to write anything, give it four lines of context: (1) who the client is and what they sell, (2) what they told you they want, in their words, (3) the outcome they actually care about - usually money, time or peace of mind, and (4) how you work - your process, your tone, your timeline.",
                    "That's it. Four lines of context transforms a generic proposal into a targeted one, because the AI stops guessing and starts assembling. The models are excellent at structuring information you give them. They are terrible at inventing information you didn't.",
                    "Throughout this book you'll learn the full method: how to build a client machine that finds, wins, delivers and retains - with AI doing the heavy lifting and you doing the thinking. But if you only remember one thing, remember the four lines. They will improve every prompt you ever write.",
                    "Action steps: (1) Write down the last proposal you sent. (2) Count how much client-specific context you gave the AI before it wrote. (3) If it was less than four lines, you now know why it failed.",
                ],
            },
            {
                "title": "The Client Machine Method: Context → Constraint → Voice",
                "paras": [
                    "Every good AI output follows the same three-stage recipe. Think of it as Context → Constraint → Voice. Miss a stage and the output breaks in a predictable way.",
                    "Context is everything the AI needs to know but cannot guess: the client, the industry, the history, the goal. Most freelancers skip this and wonder why output is generic. If you feed the AI the client's actual words from their brief or your call notes, the output will use their language - and clients notice when you speak their language.",
                    "Constraints are the rules that keep the output usable: word count, tone, banned phrases, structure. Without constraints, the AI writes the way the average internet writes - which is to say, forgettable. With constraints like 'under 120 words, no corporate phrases, one question at the end', the output gets sharp. Constraints are also where you kill the AI tell: ban 'I hope this finds you well', ban 'delve', ban 'in today's fast-paced world'.",
                    "Voice is the hardest stage, because it's the most personal. The AI doesn't know how you talk until you tell it. Paste a sample of your own writing into the prompt - an old email you were proud of - and say 'write like this'. You'll be amazed how much of your voice transfers.",
                    "A practical way to build all three stages without retyping them: keep a 'system prompt' file with your voice sample and your standard constraints, and paste it at the start of every working session. Five minutes of setup, hours of better output.",
                    "The rest of this book applies the method to each stage of the freelance cycle. The method never changes - only the context does.",
                    "Action steps: (1) Find one email you wrote that a client praised. (2) Create a text file with your standard constraints (tone, length, banned phrases). (3) Next time you prompt, paste both. Compare the output to your usual.",
                ],
            },
            {
                "title": "Outreach & Proposals That Win",
                "paras": [
                    "Outreach fails for one reason more than any other: it's about you. 'I am a freelance designer with five years of experience...' - the prospect has already stopped reading. Winning outreach is about them: something specific about their business, connected to a problem you can solve.",
                    "The AI is excellent at the mechanics of outreach once you give it the raw material. What it cannot do is research. So your job, before you prompt, is five minutes of real work: open the prospect's website, find one recent change (a new hire, a new product, a new location), and paste that into the prompt. The output will open with that detail, and the prospect will feel seen. That feeling is what gets replies.",
                    "Proposals have a similar rule: sell the outcome, not the hours. Clients don't buy '30 hours of design work'. They buy 'a website that turns visitors into bookings'. When you prompt for a proposal, lead with the outcome you heard them ask for, then show the work that produces it.",
                    "Structure your proposal prompts like this: (1) their goal, in their words, (2) the outcome your work delivers, (3) the deliverables week by week, (4) what you need from them, (5) two pricing options - full and lean. The AI will assemble this faster than you can type it, and the two-option structure does the selling for you: the full option makes the lean one feel reasonable, and the lean one keeps the door open.",
                    "One more thing: follow-up. Most deals are won by the person who follows up without being annoying. Use the AI to write a follow-up that adds value - a relevant link, a free addition, a question - rather than a reminder that you exist. Three sentences. Then move on.",
                    "Action steps: (1) Pick 5 prospects. (2) Spend 5 minutes researching each. (3) Run the outreach prompt with your research. (4) Send, and log which detail each message opened with.",
                ],
            },
            {
                "title": "Money Talks: Scope, Rates & Difficult Conversations",
                "paras": [
                    "The most expensive words in freelancing are 'sure, I can add that'. Scope creep is how profitable projects become unprofitable ones, and it happens one polite request at a time. The fix is not rudeness - it's a system.",
                    "Your system has three rules. Rule one: the scope is written down. If the agreement exists only in your memory, every request is negotiable. Rule two: additions have prices. When a client asks for extra work, the answer is not 'okay' and not 'no' - it's 'yes, that's outside the current scope, it'll be GH₵ X or Y hours'. Rule three: you say it in writing, kindly.",
                    "This is where AI earns its keep in the money conversations. Writing 'no' to a client is emotionally hard; writing it well is harder. The prompts in the companion pack (PKG-FRE-02) give you the exact words for scope creep, late invoices, rate objections and silent clients - firm without being rude, warm without being weak.",
                    "Let's talk rates, because most freelancers undercharge and know it. The number that feels 'too high' is usually the number you should quote. When a prospect says you're expensive, the correct move is not to drop the price - it's to reframe the value and offer a scope reduction. A client who accepts a cheaper version of your work is still a client who values the work; a client who only accepts a cheaper you is a race to the bottom.",
                    "Invoices deserve the same system. Send them on time, chase them on schedule (48 hours after due date, politely; then firmly; then with consequences), and never apologize for being paid for work you did. The AI can draft every one of these messages in your voice - you just have to send them.",
                    "Action steps: (1) Write down the scope of your current project in one paragraph. (2) Add a line: 'any work outside this scope is billed at GH₵ X/hour'. (3) Send it to the client as a friendly confirmation. Watch how many 'quick favours' disappear.",
                ],
            },
            {
                "title": "The Prompt Workbench: 15 Core Prompts, Explained",
                "paras": [
                    "This chapter is the workbench: fifteen prompts you'll use every week, each explained - what it does, why it works, and how to customize it. They're also in the downloadable pack (PKG-FRE-01/02/03) in Word and PDF so you can copy-paste without retyping.",
                    "The Client Machine core list: (1) Cold outreach that gets replies - lead with a specific observation about the prospect; (2) Proposal that sells the outcome - outcome first, deliverables second, two pricing options; (3) Discovery call opener - a 30-second opening plus five open questions; (4) Follow-up that doesn't nag - three sentences that add value; (5) Lean-scope negotiation - keep the core, cut the extras; (6) Testimonial request - fill-in-the-blank starters make it easy; (7) Win-back message - a memory, news, and an incentive; (8) Profile bio - three versions, results-first, story, contrarian.",
                    "The Money Talks core list: (9) Scope-creep reply - acknowledge, explain, price it; (10) Invoice chase first reminder - assume oversight, not malice; (11) Final invoice notice - facts, deadline, consequence; (12) The 'too expensive' reply - reframe, reduce scope, hold the rate; (13) The silent client - the deadline-and-consequence message; (14) Deposit request - frame it as standard practice; (15) The clean exit - end the relationship with gratitude and zero drama.",
                    "Why these fifteen? Because they cover the three moments where freelancers lose the most money: finding clients (1-4), negotiating (5, 8-9, 12-14), and retaining relationships (6-7, 10-11, 15). Each one follows the Context → Constraint → Voice method from chapter two.",
                    "A note on customization: prompts are not incantations. The AI doesn't respond to magic words - it responds to information. Every bracket you fill with a real detail improves the output by an order of magnitude. A prompt with five filled brackets will beat a 'perfect' prompt with none.",
                    "Action steps: (1) Open the pack and pick the three prompts you need this week. (2) Fill every bracket before running. (3) Save the outputs you like into a 'wins' file - your future self will thank you.",
                ],
            },
            {
                "title": "The 7-Day Implementation Plan",
                "paras": [
                    "Reading about a system changes nothing; running it changes everything. Here is your first week, one hour a day.",
                    "Day 1 - Foundation. Create your system prompt file: your voice sample, your constraints, your banned phrases. Test it on one output and refine. Day 2 - Research. List 10 prospects. Spend five minutes each on real research - one specific observation per prospect. Day 3 - Outreach. Run the outreach prompt with your research, send 10 messages. Log the opening line of each. Day 4 - Follow-up. Draft follow-ups for last week's proposals that add value. Send them. Day 5 - Money talks. Write your scope-confirmation paragraph and send it to your current client. Draft your next invoice chase schedule. Day 6 - Systems. Set up your invoice template, your deposit rule, and your 'no' template. Automate anything that repeats. Day 7 - Review. Count: replies, conversations, proposals sent, money collected. Adjust what didn't work. Repeat.",
                    "The machine doesn't need to be perfect on day one. It needs to exist. Every week you'll fill more brackets, refine your voice file, and build a 'wins' library of outputs that worked - and the machine gets stronger on its own.",
                    "One final reminder: the AI is your assistant, not your reputation. Every message it drafts carries your name. Read everything before it goes out, fix what sounds off, and only send what you'd sign. The machine handles the heavy lifting; you handle the trust.",
                    "Action steps: Start Day 1 tonight. The hour you spend setting up your system prompt file is the highest-ROI hour in this entire book.",
                ],
            },
        ],
    },
    {
        "id": "ebk-mkt-01",
        "sku": "EBK-MKT-01",
        "title": "Human-Sounding AI Copy",
        "subtitle": "Writing that doesn't scream ChatGPT",
        "author": "Obed Cudjoe",
        "desc": "How to make AI write copy that doesn't scream ChatGPT - voice briefs, de-AI editing and prompt patterns for ads, emails and landing pages.",
        "category": "marketing",
        "price": 185,
        "pages": 36,
        "toc": [
            "The AI Tell: Why Everyone Recognizes ChatGPT Copy",
            "The Voice Brief: Teaching AI Your Brand Voice in 10 Minutes",
            "The De-AI Editing Pass: 3 Rounds to Human",
            "Prompt Patterns for Ads, Emails & Landing Pages",
            "Your Voice Library: Checklists & 30-Day Plan",
        ],
        "blurb": "The anti-generic playbook. Read it in an evening, use it the next morning.",
        "chapters": [
            {
                "title": "The AI Tell: Why Everyone Recognizes ChatGPT Copy",
                "paras": [
                    "You've felt it reading an article, an ad, a LinkedIn post: a certain smoothness. Balanced sentences. A tidy structure. And absolutely nothing that sounds like a human made a choice. That's the AI tell - and once you see it, you can't unsee it.",
                    "The tell is not one thing. It's a cluster of tells. The em-dash that shows up three times per paragraph. The 'it's not just X, it's Y' construction that appears in every AI-written piece on the internet. The rhythm that never varies - long sentence, short sentence, long sentence, perfectly alternating. The total absence of anything specific: no odd detail, no unfashionable opinion, no sentence that a hundred other writers wouldn't write.",
                    "Why does this happen? Language models are trained to predict the most likely next word. The most likely word is the average word. The most likely structure is the average structure. Left to their own devices, they produce the average of all copy ever written - which is why AI copy feels like it was written by a committee of nobody.",
                    "The good news: the average is avoidable. Models are capable of surprising, specific, opinionated writing - but they need to be pushed off the average. That push comes in two forms: constraints that forbid the average moves, and inputs that give them something specific to work with. Both are in your control.",
                    "This book is the control panel. Chapter two builds the voice brief that teaches AI to sound like your brand. Chapter three is the editing pass that removes the tells from anything already written. Chapter four gives you prompt patterns for ads, emails and landing pages that start specific and stay specific.",
                    "The goal is not to disguise AI writing as human writing. The goal is writing that happens to be good - and good writing, whether a human or a model drafted it, is specific, rhythmical and a little bit strange. You're about to learn how to get there on purpose.",
                    "Action steps: (1) Find one piece of AI-generated copy you've published. (2) Circle every em-dash, every 'it's not just X' and every sentence that could appear in any article about any topic. (3) You now have your first editing list.",
                ],
            },
            {
                "title": "The Voice Brief: Teaching AI Your Brand Voice in 10 Minutes",
                "paras": [
                    "Most brands don't have a voice; they have a vibe. A vibe can't be pasted into a prompt. A voice can. The difference is a voice brief - a document that tells the AI exactly how your brand talks, in terms it can follow.",
                    "A voice brief has five sections, and you can write all five in ten minutes. Section one: three words that describe how you sound (e.g. 'plain, wry, direct'). Section two: three words you'd never use (e.g. 'synergy, leverage, delightful'). Section three: sentence rhythm - short or long? fragments allowed? Section four: what you're willing to say that others won't - your contrarian positions. Section five: three real samples of your best writing, pasted verbatim.",
                    "Section five is the secret weapon. A model can imitate a described voice about as well as you can imitate a described accent. But give it three examples of the actual thing - like an actor listening to a voice recording - and the imitation sharpens dramatically. Your old emails, your best tweets, your most-mailed newsletter: those are your voice samples.",
                    "Here's the ten-minute build: minutes 1-3, write the three words, the banned words and the rhythm notes. Minutes 4-6, write your two contrarian positions (if you can't think of any, your voice needs work - brands without positions sound like everyone). Minutes 7-10, find and paste the three samples. Save it as a file. That's the brief.",
                    "Now use it: at the top of every working session, paste the brief, then say 'now write [task] in this voice'. You'll still need editing - chapter three - but the output will arrive closer to your voice than anything you've gotten before.",
                    "Action steps: (1) Write your five-section voice brief in the next 10 minutes. (2) Run one ad prompt with and one without the brief. (3) Compare - and never run without again.",
                ],
            },
            {
                "title": "The De-AI Editing Pass: 3 Rounds to Human",
                "paras": [
                    "Editing AI copy is not fixing typos. It's a three-round pass that strips the average and restores the specific. Each round takes about five minutes per page, and each targets one layer of the tell.",
                    "Round one: structure. Read the copy aloud. Mark every sentence you would never say in conversation. Rewrite those as you'd actually speak - fragments, contractions, the occasional sentence that starts with 'and'. The ear is a brutal editor; if it sounds like a voiceover, it sounds like AI. This round fixes rhythm.",
                    "Round two: specificity. The AI wrote in categories; you edit into particulars. Replace every noun with a real thing: 'customers' becomes 'boutique owners in Osu'; 'results' becomes 'bookings up 30% in six weeks'. Add one detail only you know - a client story, a number from your own dashboard, an odd fact. Specificity is the fastest way to sound human, because AI can't invent your history and won't.",
                    "Round three: opinion. Find the places where the copy hedges - 'arguably', 'can help', 'may be'. Humans don't hedge when they believe something. Replace hedges with positions: 'this works' instead of 'this can work'. If the copy has no positions at all, add one: the thing you believe that your competitors won't say. Opinion is the final tell-remover.",
                    "Three rounds, fifteen minutes a page, and the copy reads like a human who cares. Over time you'll internalize the rounds and do them in one pass - but always do the pass. The moment you skip editing is the moment your readers feel the tell.",
                    "Action steps: (1) Take the copy you circled in chapter one. (2) Run the three rounds on one page. (3) Before-and-after: read both aloud. Keep the after.",
                ],
            },
            {
                "title": "Prompt Patterns for Ads, Emails & Landing Pages",
                "paras": [
                    "This chapter is the pattern library: four prompt structures that consistently produce copy closer to human, plus the constraints that make them work. Use them with your voice brief from chapter two.",
                    "Pattern one: the outcome-first ad. Prompt structure: audience, outcome, proof, then 'write 5 headlines under 8 words, each promising one outcome'. The constraint 'one outcome per headline' forces specificity; the proof line gives the model real material instead of averages. This pattern produces ads that read like a confident person made a claim.",
                    "Pattern two: the objection-crushing email. Prompt structure: the offer, the list's last objection (write it as a real quote), then 'write a 200-word email that opens with the objection, answers it with one proof point, and closes with one CTA'. Opening with the objection makes the email feel like a conversation, not a broadcast - the single most human move in email marketing.",
                    "Pattern three: the story landing page. Prompt structure: the customer, the moment they nearly gave up, the solution, the result, then 'write a landing page hero, subhead and 3 sections in the shape of a story: before, turning point, after'. Stories are specific by nature - they contain people, times and places - which is exactly what AI copy lacks by default.",
                    "Pattern four: the banned-phrase list. Every prompt in this book works better with a short list of what the AI may not say. Start with: 'I hope this finds you well', 'in today's fast-paced world', 'game-changer', 'unlock the power', 'seamless', 'elevate'. Six bans remove half the tells instantly.",
                    "The common thread: every pattern gives the AI something real to work with (proof, objections, stories) and something to avoid (the banned list). Real material plus constraints equals copy that doesn't sound like the average of the internet - because it isn't.",
                    "Action steps: (1) Rewrite one live ad using pattern one. (2) Rewrite one email using pattern two. (3) Run both through the three editing rounds. Ship the better versions.",
                ],
            },
            {
                "title": "Your Voice Library: Checklists & 30-Day Plan",
                "paras": [
                    "The final chapter is about compounding. Every piece of copy you write - and every prompt that produced it - is an asset. The brands that sound most human aren't the most talented; they're the most consistent. Consistency comes from a system, and your system is the voice library.",
                    "The library has four shelves. Shelf one: your voice brief (chapter two), updated monthly. Shelf two: your wins - every piece of copy that performed, with the prompt that produced it. Shelf three: your banned lists - the phrases your brand will never say, growing as you spot new tells. Shelf four: your proof bank - results, testimonials and numbers, ready to paste into any prompt.",
                    "Here's the 30-day plan. Week one: build the brief, run every prompt with it, start the wins shelf. Week two: add the three-round editing pass to every draft; move your best two pieces to the wins shelf. Week three: build the proof bank - dig out five real results and paste them everywhere. Week four: review the month - which prompts produced the most keepers? Promote those to your favourites and delete the rest.",
                    "By day 30 you won't recognize your AI output. The same model, the same tools - but now fed with your voice, your proof and your constraints, and edited with your ear. That's the whole game: not better AI, a better system around it.",
                    "One caution as you go: never publish AI copy unedited, no matter how good the prompt. The tells hide in plain sight, and your readers have been trained to see them. The system exists to make the editing fast - not to make it unnecessary.",
                    "Action steps: (1) Create the four shelves today. (2) Add your first win tonight. (3) Revisit this page in 30 days - and count how many 'wins' you've accumulated.",
                ],
            },
        ],
    },
    {
        "id": "ebk-smb-01",
        "sku": "EBK-SMB-01",
        "title": "The Small Business AI Playbook",
        "subtitle": "Marketing, reviews & ops in your spare time",
        "author": "Obed Cudjoe",
        "desc": "A 2-hour setup plus a 30-minute weekly routine that lets AI handle marketing, reviews, customer service and admin.",
        "category": "smb",
        "price": 175,
        "pages": 44,
        "toc": [
            "The 2-Hour AI Setup for Busy Owners",
            "Marketing That Runs Itself (Social, Ads, Reviews)",
            "Customer Service Without Hiring",
            "Ops & Admin: SOPs, Invoices, Scheduling",
            "The SMB Prompt Library: 15 Core Prompts",
            "Your Weekly 30-Minute AI Routine",
        ],
        "blurb": "No team, no budget, no time - and still a marketing presence that looks professional.",
        "chapters": [
            {
                "title": "The 2-Hour AI Setup for Busy Owners",
                "paras": [
                    "You don't have a marketing team. You have a shop, a phone, and whatever hours are left after the day actually runs. This book is for you: a system that turns AI into your part-time marketing department, review manager and admin clerk - for two hours of setup and thirty minutes a week.",
                    "The setup has four parts, and you can finish all of them in one evening. Part one: choose your tool. ChatGPT, Claude or Gemini - any of them works. What matters is that you use the same tool every time, so you can build history and favourites. Part two: write your business brief - a paragraph about what you sell, who buys it, your tone, and your location. You'll paste this at the top of every working session; it's the context that stops AI output from being generic.",
                    "Part three: collect your proof. Five real customer results - a compliment, a repeat order, a number (bookings, sales, reviews). You'll paste these into review replies, ads and posts. Proof is what separates marketing that works from marketing that looks like marketing. Part four: save the core prompts - the ones in chapter five of this book - into a document or favourites. Ten minutes to save, hours saved forever.",
                    "Two hours, four parts, done. The rest of this book shows you what to do with the system - and what to do when the system is working.",
                    "Action steps: (1) Book two hours this week. (2) Write your business brief in ten minutes. (3) Collect five proof points from your phone's photos, messages and reviews. Save everything into one file.",
                ],
            },
            {
                "title": "Marketing That Runs Itself (Social, Ads, Reviews)",
                "paras": [
                    "The secret of small-business marketing is not brilliance; it's consistency. A shop that posts three times a week for a year beats a shop that posts brilliantly once. AI removes the effort that kills consistency - the 'what do I post' question - so consistency becomes possible.",
                    "Social: once a week, give the AI your week - what happened, what sold, what you noticed - and ask for three posts. The prompts in chapter five turn your real week into captions with your voice. The rule: every post starts from something real that happened. AI-generated ideas from thin air are how accounts start sounding like everyone else's.",
                    "Ads: before spending a cedi, use the ad prompts to draft three angles and test them small - GH₵ 20 a day tells you more than a month of guessing. The AI writes the copy; your phone's photos are the creative. Local targeting (5-15 km around you) turns a tiny budget into real foot traffic.",
                    "Reviews: the highest-ROI marketing in small business is asking happy customers for reviews and answering every single one. The review prompts draft the asks and the replies in minutes. Reply to positive reviews in 48 hours and negative ones in 24 - speed is a signal, and future customers read how you handle problems before they ever walk in.",
                    "That's the whole marketing department: three posts a week, one small ad test, a review system. Thirty minutes a week keeps it running. The machine does the typing; you supply the reality.",
                    "Action steps: (1) This week, run the three-posts prompt with your real week. (2) Reply to every review you've missed, using the reply prompts. (3) Start your review-request habit: one message per happy customer, sent within two hours.",
                ],
            },
            {
                "title": "Customer Service Without Hiring",
                "paras": [
                    "Customers forgive slow service; they don't forgive ignored messages. But you physically cannot answer every WhatsApp, comment and review while also running the business. The answer is not hiring - it's templates with a human on top.",
                    "Start by writing down the twenty messages you receive most: price enquiries, hours, availability, complaints, compliments, the same three questions every week. For each one, use the prompts in chapter five to draft a reply in your voice. Save them as favourites. Now the first response to 80% of messages is a one-tap send - with your name on it.",
                    "Complaints deserve more care. The rule: never reply angry, never reply publicly before replying privately, and always move the fix offline ('message me and we'll sort it today'). The complaint-reply prompt drafts a calm, professional response in seconds - you add the specifics, and the specifics are what make it human.",
                    "When the AI replies, it's a template. When you add one personal line - the customer's name, the product they bought, what you'll actually do - it becomes service. That one line is the difference between 'they use chatbots' and 'they actually care'. Templates give you the speed; your line gives you the reputation.",
                    "Action steps: (1) List your twenty most-received messages. (2) Draft replies for the top five tonight. (3) Attach the 'one personal line' rule to each.",
                ],
            },
            {
                "title": "Ops & Admin: SOPs, Invoices, Scheduling",
                "paras": [
                    "Behind every smooth-running small business is a pile of boring documents: standard operating procedures, invoices, schedules, policies. They don't need to be beautiful. They need to exist - and AI makes 'exist' achievable in minutes.",
                    "SOPs: the moment you find yourself explaining how to do something for the third time, write it down. 'Explain how to close the shop, in steps, so a new hire could follow it' - the AI produces the first draft; you fix the details. Ten SOPs cover most businesses: opening, closing, handling cash, dealing with complaints, restocking, cleaning, the weekly checklist. Your staff will thank you; your future self will thank you.",
                    "Invoices and policies: the AI drafts your invoice template language, refund policy, late-payment note and terms - in plain language, not legalese. Localize everything: prices in cedis, references to MoMo payment, your actual hours. Templates that exist get used; policies that live only in your head get improvised.",
                    "Scheduling and planning: use the AI for the weekly plan ('here's what happened this week, make next week's to-do list') and the monthly review ('here are my numbers, what should I focus on?'). These two prompts alone replace a business coach for most owners - because the discipline is the coaching, and the AI supplies the discipline.",
                    "Action steps: (1) Write your three most important SOPs this week. (2) Draft your refund and late-payment lines. (3) Run the weekly-plan prompt every Sunday - set a phone reminder.",
                ],
            },
            {
                "title": "The SMB Prompt Library: 15 Core Prompts",
                "paras": [
                    "This chapter is your toolkit: fifteen prompts, each explained so you know when to use it and how to make it yours. They're in the companion pack (PKG-SMB-01) in Word and PDF.",
                    "Marketing: (1) Three posts from my week - feed it what actually happened; (2) Google review reply, positive - thank by name, mention a detail, invite back; (3) Google review reply, negative - apologize, stay calm, move offline; (4) Review request - send within two hours of the happy moment; (5) Local ad, three angles - small budget, tight radius; (6) Win-back message - a memory, what's new, an incentive; (7) Seasonal promo ideas - pick one, execute well.",
                    "Service: (8) Price enquiry reply - answer, then one value line; (9) Complaint reply - calm template plus your personal line; (10) Common question answers - the twenty-message list, drafted once; (11) Thank-you message for regulars - make loyalty visible.",
                    "Ops: (12) SOP writer - 'explain [task] so a new hire could do it'; (13) Refund policy draft - plain language, local rules; (14) Weekly plan - Sunday, ten minutes, real week in, next week out; (15) Monthly numbers review - revenue, what sold, what to focus on.",
                    "The rules of the library: fill every bracket with something real; run marketing prompts with real material; never send a template without your personal line; and once a month, delete prompts you never use - a short library you use beats a long one you don't.",
                    "Action steps: (1) Bookmark or save these fifteen. (2) This week, run prompts 1, 2 and 14. (3) Next week, add one more. The system compounds.",
                ],
            },
            {
                "title": "Your Weekly 30-Minute AI Routine",
                "paras": [
                    "Systems fail when they demand more time than you have. This one demands thirty minutes a week, on a schedule you choose - Sunday evening works for most owners. Set the reminder now.",
                    "Minutes 0-5: the weekly plan. Paste last week's reality into prompt 14: what happened, what sold, what broke, what's coming. Get the week's to-do list back, prioritized. Minutes 5-15: marketing. Run prompt 1 with your real week: three posts. Draft the review replies (prompt 2 or 3) for anything new. One ad variant if you're testing. Minutes 15-25: service. Clear the message backlog with the templates - but add your personal line to every reply. Minutes 25-30: ops and review. Update any SOP that proved wrong this week. Check the month's numbers if it's month-end. Done.",
                    "That's the routine. Three posts, all reviews answered, every message handled, the week planned - thirty minutes. The compounding happens quietly: a month of consistent posts, a stack of answered reviews, a library of SOPs, and a business that looks - from the outside - like it has a marketing department.",
                    "When things go wrong - a bad review goes viral, a complaint spirals - the routine still holds: the same prompts, the same calm templates, plus your personal line. Small businesses survive chaos on systems, not heroics.",
                    "Final advice from someone who runs this exact system: the first week feels like effort, the fourth week feels like routine, and the twelfth week is when a customer mentions 'your social media is really active lately'. That's the moment you'll know it's working.",
                    "Action steps: (1) Set the Sunday-evening reminder right now. (2) Run the first 30-minute session this week. (3) In twelve weeks, count how many customers mentioned your marketing.",
                ],
            },
        ],
    },
]

EXTRA_EBOOKS = [
    {
        "id": "ebk-cre-01",
        "sku": "EBK-CRE-01",
        "title": "The Creator Script System",
        "subtitle": "Hooks, retention & packaging that work",
        "author": "Obed Cudjoe",
        "desc": "A retention-first scripting framework - hooks, beat sheets, Shorts, titles and thumbnails.",
        "category": "creators",
        "price": 165,
        "pages": 40,
        "toc": [
            "Why Generic Scripts Die in the First 15 Seconds",
            "The Retention Map: Hooks, Loops & Payoffs",
            "Long-Form Scripting That Sounds Like You",
            "Shorts, Titles & Thumbnails: Packaging That Stops the Scroll",
            "The Creator Prompt Workbench",
            "From Script to Upload: Your Weekly System",
        ],
        "blurb": "The difference between a video that dies and one that holds is structure, not talent.",
        "chapters": [
            {
                "title": "Why Generic Scripts Die in the First 15 Seconds",
                "paras": [
                    "The average viewer decides in the first 15 seconds whether to keep watching. Most creators lose that decision before they've said anything interesting - not because they lack talent, but because their opening is generic.",
                    "'Hey guys, welcome back to the channel. In today's video we're going to talk about...' — seven seconds gone, zero reasons to stay. The viewer's thumb is already moving. The generic opening is the single most common cause of early drop-off, and it's completely fixable.",
                    "The problem is that most scripts are written like essays: introduction, then context, then the point. Video is the opposite. The point must arrive in the first sentence, wrapped in tension, because the viewer hasn't promised you anything yet.",
                    "This book is a system for writing scripts that hold attention: how to open with a hook that creates an open loop, how to structure beats so interest rises instead of flatlining, how to write for the ear instead of the page, and how to package the video (title, thumbnail, Shorts) so the click and the content promise the same thing.",
                    "None of this requires being funny, charismatic or born-talented. It requires structure - the same structure the biggest channels use, applied deliberately. That's what the Creator Script System is: a repeatable pipeline from idea to upload.",
                    "If you only take one thing from this chapter, take this: the first 15 seconds are a separate craft from the rest of the video. Write them last, test them hardest, and never open with 'hey guys'.",
                ],
            },
            {
                "title": "The Retention Map: Hooks, Loops & Payoffs",
                "paras": [
                    "Retention is not about keeping viewers interested the whole time - that's impossible and unnecessary. It's about keeping them curious in a loop: open a question, pay it off, open the next one before the previous closes. This is the retention map.",
                    "The map has three tools. Hooks open loops: a claim, a question, a contradiction, a promise ('the reason nobody tells you...'). Open loops create tension, and tension is what the brain wants to resolve. Every minute of video should contain at least one open loop.",
                    "Payoffs close loops: the moment you deliver what the hook promised. A payoff must be concrete - a number, a demonstration, an answer - or the viewer feels cheated. Cheated viewers leave and don't come back.",
                    "Callbacks are bonus payoffs: references to earlier moments in the same video (or a previous video) that reward attentive viewers. They cost nothing and they're why loyal viewers feel like insiders.",
                    "The classic map looks like this: hook (open loop 1) → setup → payoff 1 + open loop 2 → beat → payoff 2 + open loop 3 → ... → final payoff that closes everything and teases the next video. The strongest beat goes around 40% in, because that's where most drop-off peaks - a big payoff there resets attention.",
                    "Before writing a single sentence, draw the map: for each minute, what loop is open and when does it close? If you can't name the loop, neither can the viewer - and they'll leave to find one that can.",
                ],
            },
            {
                "title": "Long-Form Scripting That Sounds Like You",
                "paras": [
                    "Writing for video is writing for the ear, not the page. The ear hates long sentences, subordinate clauses and words you'd never say aloud. The ear loves fragments, contractions, and sentences that start with 'and' or 'but' - because that's how people actually talk.",
                    "Rule one: read every line aloud. If you stumble, rewrite. This single habit removes more AI-sounding and essay-sounding writing than any other technique. Your ear knows your voice better than your eye does.",
                    "Rule two: one idea per beat. A beat is 15-45 seconds: a point, an example, a mini-payoff. When you feel the need to say 'also', you've finished a beat and should start a new one. Scripts that ramble lose viewers who were never given a reason to stay for the next beat.",
                    "Rule three: specifics over abstractions. 'The algorithm rewarded consistent uploads' is forgettable. 'I posted every Tuesday for 11 weeks and video 12 got 40,000 views' is memorable. Specifics are also your anti-AI weapon - a model can generate abstractions all day, but only you know your numbers, your stories and your opinions.",
                    "Rule four: write the hook last. The opening is a compression of everything the video delivers, and you can't compress what doesn't exist yet. Script the body first, then write an opening that promises the most exciting thing in it.",
                    "And when the script is done, do the de-AI pass: remove every em-dash overuse, every 'it's not just X, it's Y', every perfectly balanced sentence. Replace them with one fragment, one question to camera, one detail only you would know. That's the difference between 'written by AI' and 'sounds like you'.",
                ],
            },
            {
                "title": "Shorts, Titles & Thumbnails: Packaging That Stops the Scroll",
                "paras": [
                    "Your video can be brilliant, and still die because the package - the title and thumbnail the viewer sees before they click - promised something else, or promised nothing at all. Packaging is not decoration; it's the first sentence of the video.",
                    "Titles: the best formats are the ones that create open loops. Numbers promise specificity ('7 signs...'), curiosity gaps promise secrets ('the reason nobody tells you...'), contrarian takes promise a fight ('stop optimizing for views'), results promise proof ('how I grew 10x in 3 months'). Write 10-15 titles, then pick the three strongest and test.",
                    "Thumbnails: the viewer's eye reads emotion first, then subject, then text. One clear subject, one readable emotion, and max three words of overlay that add information the title doesn't have. Avoid the cliches - red arrows, shocked faces, text that duplicates the title - because cliches signal low-effort content before a single frame plays.",
                    "Shorts: vertical video is a different species. The first second decides everything, the hook must land in the first two seconds, and the payoff must arrive by second 25. Structure every Short as: hook → promise → one or two quick points → payoff → follow CTA. One idea per Short - two ideas means two Shorts.",
                    "The rule that ties it all together: the title, thumbnail and first line of the video must promise the same thing. When they disagree, the viewer feels tricked - and tricked viewers click away and distrust your next upload.",
                    "Package every video like the click matters, because in the feed, the click is the whole game.",
                ],
            },
            {
                "title": "The Creator Prompt Workbench",
                "paras": [
                    "This chapter is the workbench: the core prompts from the companion packs (PKG-CRE-01/02/03), explained so you know when to use each one and how to make it yours.",
                    "The scripting set: (1) Hook bank - ten options across five proven patterns; (2) Retention beat sheet - the loop map before the script; (3) Full script from beat sheet - written for the ear; (4) Open loop creation - retrofit tension into flat sections; (5) De-AI pass - strip every tell; (6) Pattern interrupt - rescue the drop-off point.",
                    "The packaging set: (7) Title CTR bank - twelve titles across four formats; (8) Thumbnail concepts - eight options with reasoning; (9) First 5 seconds rewrite - three cold opens; (10) End screen + tease - the closing loop; (11) Description and tags - metadata that ranks; (12) Comment engine - replies that spark threads.",
                    "The system set: (13) Idea mining - fifteen ideas with angles; (14) Viewer avatar - the target behind every script; (15) Content sprint plan - batch production in one day; (16) Repurpose long into Shorts - five vertical videos from one; (17) Weekly creator review - the Sunday ritual; (18) Mini-product launch - turn authority into income.",
                    "The rules of the workbench are the same as every good tool set: fill every bracket with something real before you run the prompt; treat output as a first draft, never a final; and keep a 'wins' file of outputs that worked, so the system gets smarter as you use it.",
                    "Eighteen prompts is not a lot - but used weekly, they cover the entire pipeline from blank page to published video, and they get faster every time you use them.",
                ],
            },
            {
                "title": "From Script to Upload: Your Weekly System",
                "paras": [
                    "Creators don't fail from lack of talent; they fail from lack of a system. The weekly system here takes about two focused sessions - one for scripting, one for production - and produces one quality long-form video plus two Shorts.",
                    "Session one (2-3 hours): idea and scripting. Mine ideas (prompt 13), pick one, build the beat sheet (2), script it (3), write the hook last, run the de-AI pass (5). Then packaging: titles (7), thumbnail concepts (8), description and tags (11). The video is now 80% decided before you ever hit record.",
                    "Session two (2-4 hours): production and upload. Record in the order of beats, not the order of the script - group similar shots. Edit to the beat sheet timestamps, not by feel. Upload with the prepared metadata, publish, then run the comment engine (12) in the first hour.",
                    "Between sessions: harvest the Shorts (16) from the long video, respond to comments, and log everything - what you made, what happened, what you'd change - for the weekly review (17).",
                    "The weekly review is the compounding engine. Five minutes with the numbers - views, retention, CTR - plus the question 'what did I learn?' turns every video into data for the next one. Channels that review weekly grow; channels that don't, spin.",
                    "That's the system: two sessions, one video, two Shorts, one review. Week after week, the system beats motivation - because motivation is weather, and systems are climate.",
                ],
            },
        ],
    },
]
