# Real prompt pack content — used by scripts/generate_content.py
# Each prompt: title, when (when to use), prompt (with [PLACEHOLDERS]),
# customize (how to adapt), output (what good looks like).

PACKS = [
    {
        "id": "pkg-fre-01",
        "sku": "PKG-FRE-01",
        "title": "Freelance Client Machine: Outreach & Proposals",
        "desc": "10 copy-paste prompts for cold outreach, proposals, discovery calls and follow-ups that don't sound like AI.",
        "category": "freelance",
        "price": 75,
        "count": 10,
        "intro": "Use these prompts with ChatGPT, Claude or Gemini. Fill every [BRACKET] — the more specific your input, the better the output. Each prompt includes customization notes and an example of what good looks like.",
        "prompts": [
            {"title": "Cold outreach that gets replies",
             "when": "First message to a prospect you've never spoken to.",
             "prompt": "Write a cold outreach message from [ME - freelance role] to [PROSPECT NAME] at [COMPANY] who [WHY THEY MATTER - e.g. just hired, wrote a post, expanded]. Goal: book a 15-minute call. Lead with one specific observation about their business or a post they wrote — not about me. Keep under 120 words. End with one low-friction question. Forbidden: 'I hope this finds you well', 'I wanted to reach out', 'passionate about'.",
             "customize": "Replace the observation with something real you found. One specific line beats three generic ones.",
             "output": "A short, personal message that starts with their world, not yours."},
            {"title": "Proposal that sells the outcome",
             "when": "Sending a proposal for a project you genuinely want.",
             "prompt": "Write a project proposal for [CLIENT] for [PROJECT]. Client's goal: [THEIR GOAL]. My approach: [YOUR APPROACH - 2-3 sentences]. Timeline: [X] weeks. Budget: GH₵ [AMOUNT]. Structure: (1) the outcome they care about, (2) what I will deliver week by week, (3) what I need from them, (4) price with 2 options - full scope and a lean version. Tone: confident, plain language, no jargon. Under 400 words.",
             "customize": "Add one line they said in your discovery call - it shows you listened.",
             "output": "A proposal a busy owner can skim in 2 minutes and say yes to."},
            {"title": "Discovery call opener",
             "when": "Starting a call with a new prospect.",
             "prompt": "I have a 20-minute discovery call with [PROSPECT] at [COMPANY] about [TOPIC]. Write me: (1) a 30-second opener that names the pain they likely have, (2) 8 discovery questions that move from their situation to their goals to budget, (3) a polite way to ask 'what happens if we do nothing'. Keep questions open-ended, no yes/no.",
             "customize": "Pick the 5 questions most relevant to their industry.",
             "output": "A call script that makes you sound like you've done this a hundred times."},
            {"title": "Follow-up that doesn't nag",
             "when": "3-5 days after sending a proposal with no reply.",
             "prompt": "Write a follow-up email to [CLIENT] about my proposal for [PROJECT] sent on [DATE]. Keep it to 3 sentences max: (1) a value reminder tied to their goal, (2) one new small thing I can include for free, (3) a soft deadline question like 'shall I hold the slot for next week?'. Tone: helpful, zero pressure, no guilt. Forbidden: 'just following up', 'touching base'.",
             "customize": "The 'new small thing' should be real and cheap to deliver.",
             "output": "A follow-up that adds value instead of begging for a reply."},
            {"title": "Proposal negotiation - lean scope",
             "when": "Client says the budget is too high.",
             "prompt": "The client loves my proposal for [PROJECT] but says GH₵ [AMOUNT] is above budget. Write a reply that: (1) validates the budget reality, (2) offers a lean version cutting [LIST - e.g. extra revision round, bonus report] to reach GH₵ [LOWER AMOUNT], (3) explains what they keep and what they lose, (4) leaves the full version on the table. Tone: confident, not apologetic.",
             "customize": "Never cut your core deliverable - cut extras only.",
             "output": "A counter that keeps the project alive without gutting your value."},
            {"title": "Testimonial request without the cringe",
             "when": "Project delivered, client happy.",
             "prompt": "Write a short message asking [CLIENT] for a testimonial after delivering [PROJECT]. Make it easy: (1) remind them of the result in one line, (2) give them 3 fill-in-the-blank sentence starters like 'Before working with [ME]...' and 'The best part was...', (3) ask permission to publish on my site. Tone: warm, no pressure.",
             "customize": "Name the actual result (e.g. 'the site launched on time and bookings doubled').",
             "output": "A request so easy the client says yes in 2 minutes."},
            {"title": "Win-back message for old clients",
             "when": "A past client who went quiet 3+ months ago.",
             "prompt": "Write a win-back message to [PAST CLIENT] who I last worked with on [PROJECT] around [DATE]. Structure: (1) one specific memory of working together, (2) one new capability I now offer that solves their known pain [PAIN], (3) a tiny offer - free 20-minute audit or a one-off task at a fixed price. Under 120 words.",
             "customize": "Check their LinkedIn for recent news to reference.",
             "output": "A message that reopens a door without pretending nothing happened."},
            {"title": "Upwork/Clients profile bio",
             "when": "Writing your freelance profile summary.",
             "prompt": "Write a freelance profile bio for [ROLE] with [X] years of experience serving [TARGET INDUSTRY]. My best results: [RESULT 1], [RESULT 2]. Write 3 versions: (A) results-first, (B) story-driven, (C) contrarian. Each under 90 words, first-person, no buzzwords like 'results-driven', 'passionate', 'ninja'. End each with a clear 'hire me for...' line.",
             "customize": "Use numbers from real projects, not generic claims.",
             "output": "A bio that makes a stranger confident enough to message you."},
            {"title": "Pricing anchor email",
             "when": "Client asks 'how much?' before scope is clear.",
             "prompt": "Write a reply to [CLIENT] who asked for my price for [VAGUE REQUEST]. Politely explain I price on scope, not guesses, and ask 4 short questions to scope it: goal, deadline, must-haves, budget range. Then give a price range GH₵ [MIN]-[MAX] 'depending on answers'. Tone: friendly, confident. Under 150 words.",
             "customize": "Give a real range you're happy with - never quote before scope.",
             "output": "A reply that anchors your price and filters tire-kickers."},
            {"title": "Saying no to bad-fit projects",
             "when": "A project that's outside your skills or under your rate.",
             "prompt": "Write a polite refusal to [CLIENT] for [PROJECT]. Structure: (1) thank them + name the project, (2) say clearly I'm not the right fit because [REASON - scope/skills/bandwidth], (3) one genuinely useful alternative (referral, timeline suggestion, or a partial service I CAN do), (4) leave the door open. Tone: warm, zero guilt.",
             "customize": "Actually offer the referral or alternative - it builds reputation.",
             "output": "A no that leaves the client respecting you more."},
        ],
    },
    {
        "id": "pkg-fre-02",
        "sku": "PKG-FRE-02",
        "title": "Freelance Client Machine: Money, Scope & Hard Conversations",
        "desc": "10 prompts for rate negotiations, scope-creep replies, invoice chasing and saying no - firm, never rude.",
        "category": "freelance",
        "price": 85,
        "count": 10,
        "intro": "The hardest conversations in freelancing are the most profitable to get right. These prompts help you stay firm and professional - no passive-aggression, no caving.",
        "prompts": [
            {"title": "Scope-creep response",
             "when": "Client asks for work outside the agreed scope.",
             "prompt": "Write a reply to [CLIENT] who asked for [EXTRA WORK] that falls outside our agreement covering [ORIGINAL SCOPE]. Acknowledge the request, explain it's outside the agreed scope, and offer to do it as a paid addition at GH₵ [AMOUNT] (or X hours at my rate). Give them a simple yes/no choice. Tone: helpful, not apologetic, no guilt-tripping. Under 120 words.",
             "customize": "Price the addition immediately - never say 'let me see'.",
             "output": "A reply that makes extra work a business decision, not a favour."},
            {"title": "Invoice chase - first reminder",
             "when": "Invoice is 1-2 days late.",
             "prompt": "Write a friendly first reminder for invoice [#NUMBER] of GH₵ [AMOUNT] for [PROJECT], due [DATE]. Assume it's an oversight, not malice. Two sentences: one referencing the invoice, one asking if they need anything to process it. Add the payment details again. Tone: light, zero accusation.",
             "customize": "Send within 48 hours of the due date - politeness has a window.",
             "output": "A nudge that gets most invoices paid within a day."},
            {"title": "Invoice chase - firm final notice",
             "when": "Invoice is 2+ weeks late after a friendly reminder.",
             "prompt": "Write a firm final invoice notice for [#NUMBER] of GH₵ [AMOUNT], [X] days overdue. State: (1) the facts - invoice number, date, amount, reminders sent, (2) a deadline of [DATE] for payment, (3) the consequence if not paid by then: work pauses and late fee of [X]% applies. Tone: professional, calm, final. Under 150 words.",
             "customize": "Only send this if you're truly willing to pause work.",
             "output": "A notice that says 'I take my money seriously' without shouting."},
            {"title": "Rate negotiation - the 'too expensive' reply",
             "when": "Prospect says your rate is too high.",
             "prompt": "Write a response to a prospect who says my rate of GH₵ [AMOUNT] is too expensive. Do NOT lower the rate. Instead: (1) reframe the value with one specific result I've delivered [RESULT], (2) offer an alternative scope reduction if budget is the issue, (3) ask what their budget is. Tone: confident, not defensive, not apologetic.",
             "customize": "Use a real past result with numbers if you have one.",
             "output": "A reply that holds your rate while keeping the conversation open."},
            {"title": "The silent client - mid-project ghost",
             "when": "Client stops replying mid-project.",
             "prompt": "Write a follow-up to [CLIENT] who has been silent for [X] days on [PROJECT]. I need [FEEDBACK/APPROVAL/FINAL PAYMENT] to proceed. State clearly: if I don't hear back by [DATE] I will [PAUSE THE PROJECT / consider the current deliverable final and invoice]. Tone: firm and professional, not emotional.",
             "customize": "Pick a consequence you'll actually follow through on.",
             "output": "A message that ends the silence or ends the limbo."},
            {"title": "Asking for a deposit upfront",
             "when": "New client, no history, first project.",
             "prompt": "Write a short message to [CLIENT] confirming we're ready to start [PROJECT] and explaining I require a [X]% deposit (GH₵ [AMOUNT]) before kickoff, with the balance due on delivery. Keep it light and standard - frame it as 'how I work with all new clients'. One line on why (booking the time). Under 80 words.",
             "customize": "Never waive the deposit for brand-new clients.",
             "output": "A request that normalizes deposits instead of apologizing for them."},
            {"title": "Late project apology + revised date",
             "when": "You're going to miss a deadline.",
             "prompt": "Write an apology to [CLIENT] for the delay on [PROJECT]. Be specific: what happened in one honest sentence (no novel-length excuses), what's done, when they'll get the rest [NEW DATE], and one small concession (e.g. an extra revision round free). Tone: accountable, brief, no over-apologizing. Under 120 words.",
             "customize": "Announce the delay BEFORE the deadline, not after.",
             "output": "An apology that keeps trust because it comes with a plan."},
            {"title": "Handling a rude or unreasonable client",
             "when": "Client is abusive or demands impossible things.",
             "prompt": "Write a calm reply to [CLIENT] who sent [THE UNREASONABLE MESSAGE - quote briefly]. Structure: (1) acknowledge the frustration, (2) restate what I CAN do and by when, (3) set one clear boundary on communication (e.g. 'I respond to messages within 24 hours, Mon-Fri'), (4) offer to part ways professionally if that's not acceptable. Tone: ice-cold professional, zero drama.",
             "customize": "If it's truly abusive, skip to step 4.",
             "output": "A reply that protects your peace and your reputation."},
            {"title": "Pricing your package (rate calculator prompt)",
             "when": "You don't know what to charge for a new service.",
             "prompt": "Help me price a freelance [SERVICE] package. Costs: monthly expenses GH₵ [AMOUNT], taxes ~[X]%, desired monthly income GH₵ [AMOUNT]. Time per project: [X] hours. Walk me through: (1) hourly rate needed, (2) a 3-tier package (basic/standard/premium) with what each includes, (3) what GH₵ prices to put on each tier, (4) the psychology of the middle tier as the anchor.",
             "customize": "Use real numbers - the output is only as good as the inputs.",
             "output": "A pricing structure you can defend in your head."},
            {"title": "Ending a project early (client side)",
             "when": "You need to fire a client.",
             "prompt": "Write a professional message to end our working relationship after [PROJECT/PERIOD]. Structure: (1) thank them for the work together, (2) explain I'm restructuring my client load (no need for detail), (3) commit to finishing [CURRENT DELIVERABLE] or hand over files by [DATE], (4) wish them well. Tone: grateful, final, no drama. Under 100 words.",
             "customize": "Give 2-4 weeks of runway if you can.",
             "output": "A clean exit that leaves the door politely closed."},
        ],
    },
    {
        "id": "pkg-fre-03",
        "sku": "PKG-FRE-03",
        "title": "Freelance Business Engine (Full System)",
        "desc": "The complete 12-prompt system: outreach, proposal, pricing, delivery, testimonial and retention with a weekly AI routine.",
        "category": "freelance",
        "price": 145,
        "count": 12,
        "intro": "The full system. Run these prompts in order across your client cycle - find, win, deliver, retain. Combine with pkg-fre-01 and pkg-fre-02 for the complete library.",
        "prompts": [
            {"title": "Weekly client pipeline review",
             "when": "Every Monday morning.",
             "prompt": "Act as a freelance business coach. Here is my current pipeline: [PASTE: prospects, proposals, active projects, invoices with statuses]. Review it and tell me: (1) the single highest-leverage action this week, (2) which proposal is most likely to close and why, (3) which client is most at risk and why, (4) what to automate or delegate. Be blunt, no flattery.",
             "customize": "Keep a simple text log of your pipeline to paste in.",
             "output": "A 5-minute Monday review that sets the week."},
            {"title": "Ideal client profile",
             "when": "Before any outreach sprint.",
             "prompt": "Build me an ideal client profile for [MY SERVICE]. Include: industries that need this most, company size, the person I should talk to, the top 3 problems they feel daily, the words they use to describe those problems, where they hang out online, and the #1 objection they'll have to hiring me. Based on this, write 5 opening lines for outreach messages.",
             "customize": "Answer from real experience, not guesses.",
             "output": "A targeting sheet that stops you spraying messages everywhere."},
            {"title": "Outreach sprint - 10 personalized messages",
             "when": "When you have 10 real prospects.",
             "prompt": "Here are 10 prospects with one line each about them: [PASTE LIST]. For each, write a 3-sentence cold message: sentence 1 names something specific about them/their business, sentence 2 connects it to one thing I do, sentence 3 asks one small question. No templates, no 'I hope this finds you well'. Vary the openings so no two sound alike.",
             "customize": "Research each prospect for 5 minutes before running this.",
             "output": "10 messages that each feel written for one person."},
            {"title": "Discovery call -> proposal summary",
             "when": "After every discovery call.",
             "prompt": "Here are my raw notes from a discovery call with [CLIENT]: [PASTE NOTES]. Produce: (1) a 5-line summary of what they need, (2) their stated goal and their real goal, (3) the 3 questions I should still answer before proposing, (4) a proposed scope outline with deliverables. Flag anything they said that contradicts the brief.",
             "customize": "Paste your notes right after the call - don't let them cool.",
             "output": "A call summary that makes the proposal 10x faster to write."},
            {"title": "Deliverable handover email",
             "when": "Sending finished work.",
             "prompt": "Write the handover email for [PROJECT] to [CLIENT]. Include: (1) what's attached/delivered, (2) a 3-bullet summary of what was done and the key decisions, (3) what I need from them next (review by [DATE], feedback), (4) the next step after approval. Tone: confident, brief. Under 150 words.",
             "customize": "Attach a short Loom/voice note for complex deliverables.",
             "output": "A handover that makes 'approve this' the only next step."},
            {"title": "Case study from a finished project",
             "when": "After a successful project.",
             "prompt": "Turn this project into a case study: client [CLIENT], problem [PROBLEM], what I did [WORK], result [RESULT WITH NUMBERS]. Write it in the Problem -> Approach -> Result format, under 300 words, third person, with one pull-quote I can ask the client to confirm. End with a 1-line 'what this means for businesses like yours'.",
             "customize": "Ask the client to approve the numbers before publishing.",
             "output": "A case study you can put on your site and in proposals."},
            {"title": "Retention check-in for ongoing clients",
             "when": "Monthly, for retainer clients.",
             "prompt": "Write a monthly check-in message to [RETAINER CLIENT]. Structure: (1) this month's wins - name 2-3 specific things delivered, (2) one number that moved if available, (3) what's next month, (4) one question to surface anything they need. Tone: like a partner, not a vendor. Under 120 words.",
             "customize": "Send it on the same day every month - consistency builds trust.",
             "output": "A check-in that makes retainer renewals feel obvious."},
            {"title": "Referral request that works",
             "when": "After a great delivery or a happy testimonial.",
             "prompt": "Write a referral request to [CLIENT] who just praised my work on [PROJECT]. Structure: (1) thank them for the kind words, (2) explain my business grows through introductions, (3) ask them to think of 2-3 people who could use [MY SERVICE] and offer a template I can send directly, (4) sweetener: a small reward for referrals that close (e.g. discount on next project).",
             "customize": "Send it while the glow of delivery is still fresh.",
             "output": "A request that turns happy clients into your sales team."},
            {"title": "Quarterly rate review",
             "when": "Every 3 months.",
             "prompt": "Help me review my freelance rates. Current rate: GH₵ [AMOUNT]/[HOUR OR PROJECT]. Since my last review: [WHAT CHANGED - skills, demand, results, inflation]. Analyze: (1) should I raise rates and by how much, (2) which existing clients to grandfather vs. raise, (3) how to announce the change without losing clients, (4) a script for telling my 2 biggest clients. Be specific.",
             "customize": "Raise at least one client's rate per quarter, every quarter.",
             "output": "A rate strategy and the exact words to deliver it."},
            {"title": "Automating the busywork with AI",
             "when": "Once a month.",
             "prompt": "Here is a list of everything I did last week for my freelance business: [PASTE LOG]. Categorize each task as: client revenue work / admin / marketing / learning. For the admin bucket, suggest 3 specific automations (tools or prompt workflows) that could remove or shrink each task. Rank by time saved vs. setup effort. Be realistic, no pipe dreams.",
             "customize": "Actually log your week - guessing defeats the purpose.",
             "output": "A monthly automation shortlist that buys back hours."},
            {"title": "Handle a bad review or public complaint",
             "when": "A client criticizes you publicly.",
             "prompt": "Draft a public response to this review/complaint: [PASTE REVIEW]. Rules: (1) thank them for the feedback, (2) acknowledge the specific issue without admitting fault blindly, (3) state what you've done or will do to fix it, (4) move it offline ('message me so we can sort this properly'). Never argue, never mention their tone. Under 100 words.",
             "customize": "Wait 30 minutes before posting so it's calm, not reactive.",
             "output": "A response that makes you look professional to everyone watching."},
            {"title": "Personal brand statement",
             "when": "Refreshing your bio, site or LinkedIn.",
             "prompt": "Write my freelance brand statement. I help [TARGET] achieve [OUTCOME] through [MY METHOD/SERVICE]. My proof: [RESULTS]. My differentiator: [WHAT MAKES ME WEIRD/UNIQUE]. Write 3 versions: 10 words, 50 words, 150 words. Each must pass this test: would a stranger in my industry read it and remember me tomorrow?",
             "customize": "The differentiator should be specific - 'I work with Ghanaian e-commerce brands' beats 'I'm passionate about results'.",
             "output": "A brand statement with versions for every surface you publish on."},
        ],
    },
    {
        "id": "pkg-mkt-01",
        "sku": "PKG-MKT-01",
        "title": "Copy That Converts: Ads & Emails",
        "desc": "10 prompts for ad headlines, hooks, sales emails and landing-page copy built on proven direct-response patterns.",
        "category": "marketing",
        "price": 85,
        "count": 10,
        "intro": "Direct-response patterns that have worked for a century, applied to AI. Fill the brackets, kill the AI-tell, and the copy will sound like a writer - because the structure is doing the work.",
        "prompts": [
            {"title": "Ad headline bank (AIDA)",
             "when": "Starting a new ad campaign.",
             "prompt": "Write 15 ad headlines for [PRODUCT/SERVICE] targeting [AUDIENCE] who wants [OUTCOME] and fears [PAIN]. Use these proven patterns, 3 each: (1) specific-number results, (2) how-to, (3) before/after, (4) objection crusher, (5) curiosity gap. Max 8 words each. No clickbait the ad can't deliver on. Mark the 3 strongest.",
             "customize": "Use real numbers from your results, not invented ones.",
             "output": "A headline bank you can A/B test for weeks."},
            {"title": "Sales email - problem-agitate-solve",
             "when": "Launching a promo or new offer to your list.",
             "prompt": "Write a sales email for [OFFER] to my list of [AUDIENCE]. Use the Problem-Agitate-Solve structure: open with the problem they feel daily [PROBLEM], agitate with 2 sentences on what it costs them, present [OFFER] as the solution with 3 bullet benefits, add urgency [DEADLINE/SPOTS], close with one clear CTA. Keep it 180-220 words, plain language, no em-dash overuse, no 'unlock the power'.",
             "customize": "Write the problem from real customer conversations.",
             "output": "An email that reads like it was written by one human to one human."},
            {"title": "Landing page hero + subhead",
             "when": "Building or rebuilding a landing page.",
             "prompt": "Write 5 hero headline + subheadline pairs for [OFFER] to [AUDIENCE]. Each pair must: (1) promise one specific outcome, (2) name the audience, (3) remove one objection in the subhead (price, time, risk). Add a 5-word CTA button text for each. Formats: outcome-first, enemy-first, time-bound, cost-flip, contrarian.",
             "customize": "Steal the exact words your customers already use.",
             "output": "A hero section that passes the 5-second skim test."},
            {"title": "Abandoned cart email sequence",
             "when": "Carts are dying and you want the revenue back.",
             "prompt": "Write a 3-email abandoned cart sequence for [PRODUCT] at GH₵ [PRICE]. Email 1 (1 hour): friendly reminder + the main benefit. Email 2 (24 hours): address the top 2 objections [OBJECTIONS] with proof (reviews/results). Email 3 (72 hours): last chance - [INCENTIVE e.g. free shipping/discount] + gentle scarcity. Each under 100 words, distinct from the others.",
             "customize": "Use real objection-handling from your customer service chats.",
             "output": "A sequence that quietly converts 5-15% of lost carts."},
            {"title": "Facebook/IG ad copy - 3 angles",
             "when": "Launching social ads.",
             "prompt": "Write 3 ad variations for [PRODUCT] on [PLATFORM - Facebook/Instagram] targeting [AUDIENCE]: (1) hook-first - stop the scroll with a bold claim, (2) social-proof - lead with a customer result, (3) empathy - lead with their struggle. Each: 40-word primary text + 2 headlines + 1 CTA. No hashtags, no emojis except one max, no 'Are you tired of...' openings.",
             "customize": "Pair each angle with a different creative (image/video).",
             "output": "3 ads that test distinct psychological levers."},
            {"title": "Product description that sells",
             "when": "Product page copy is flat.",
             "prompt": "Rewrite this product description: [PASTE CURRENT COPY]. New version must: (1) open with the outcome, not the features, (2) translate every feature into a benefit with a mini story, (3) include a 'who this is for / who it's not for' section, (4) end with a risk-reversal line (guarantee/refund). Keep the same length or shorter. Match tone: [TONE].",
             "customize": "Steal specifics from your best customer reviews.",
             "output": "A description that sells the transformation, not the thing."},
            {"title": "Objection-handling FAQ block",
             "when": "Prospects ask the same 5 questions.",
             "prompt": "Write an FAQ block for [OFFER] answering: [LIST 5 QUESTIONS - e.g. 'is this for beginners?', 'what if it doesn't work?', 'how long does it take?', 'do I need any tools?', 'what exactly do I get?']. Format: question as the header, 2-3 sentence answer that sells without sounding salesy, each ending with a mini-CTA where natural. Under 40 words per answer.",
             "customize": "Use the actual questions from your DMs and comments.",
             "output": "An FAQ that handles objections while they're still curious."},
            {"title": "Retargeting ad for engaged visitors",
             "when": "People visited but didn't buy.",
             "prompt": "Write retargeting ad copy for people who visited [PAGE - e.g. the pricing page] but didn't buy [PRODUCT]. Assume they're interested but hesitant. Angle: 'you were this close' without being creepy - offer [BRIDGE - free guide, demo, smaller version, deadline]. 30-word primary text, 2 headlines, 1 CTA. One line must address the likely reason they left [REASON].",
             "customize": "A smaller offer beats a discount for cold-ish leads.",
             "output": "A retargeting ad that warms, not harasses."},
            {"title": "Launch email sequence (3 emails)",
             "when": "Launching anything to a cold-ish list.",
             "prompt": "Write a 3-email launch sequence for [OFFER]: Email 1 'the announcement' - what it is, who it's for, why now. Email 2 'the proof' - results/testimonials/story. Email 3 'the close' - recap benefits, deadline [DATE], what they miss if they skip it. Each 150-200 words, no hype words ('game-changer', 'revolutionary', 'insane').",
             "customize": "Space them 24-48 hours apart.",
             "output": "A launch sequence with a narrative arc, not three ads."},
            {"title": "A/B test copy variant generator",
             "when": "You have a winner but want more.",
             "prompt": "Here is a winning piece of copy: [PASTE]. Generate 4 test variants: (1) same message, shorter by 40%, (2) same message, more specific (add numbers/detail), (3) flipped to negative framing (what they lose by NOT acting), (4) first-person voice (from a customer's mouth). Keep the CTA identical. Note which element each variant changes so I can learn what moved the needle.",
             "customize": "Run one variant at a time against the control.",
             "output": "A clean A/B test plan with isolatable variables."},
        ],
    },
    {
        "id": "pkg-mkt-02",
        "sku": "PKG-MKT-02",
        "title": "Copy That Converts: Content, Social & SEO",
        "desc": "10 prompts for blog structures, social captions, SEO briefs and content calendars that keep one consistent voice.",
        "category": "marketing",
        "price": 85,
        "count": 10,
        "intro": "Content is a compounding asset - if it's structured to rank and written to be read. These prompts handle the structure so your voice stays yours.",
        "prompts": [
            {"title": "SEO blog post outline",
             "when": "Writing a post that should rank.",
             "prompt": "Create a detailed outline for a blog post targeting the keyword '[KEYWORD]' for [AUDIENCE]. Include: (1) 3 search-intent-matched title options under 60 chars, (2) an H2/H3 skeleton with the angle for each section, (3) the specific question each section answers, (4) places to add internal links to [EXISTING POSTS], (5) a FAQ block with 3 questions people also ask. Also list what the SERP results for this keyword currently cover and how we'll be more useful.",
             "customize": "Check the actual SERP before running - gaps are gold.",
             "output": "An outline that out-specs the current top 10 results."},
            {"title": "Blog post from outline",
             "when": "Outline done, first draft time.",
             "prompt": "Write the first draft of the blog post using this outline: [PASTE OUTLINE]. Target: [WORD COUNT] words for [AUDIENCE]. Rules: (1) open with the reader's problem, not 'in today's world', (2) one idea per paragraph, (3) include 3 concrete examples with real numbers, (4) no fluff transitions ('it's important to note'), (5) end with 3 actionable takeaways + 1 question for comments. Write in [TONE].",
             "customize": "Give it one specific example from your own experience.",
             "output": "A draft that needs editing, not resurrection."},
            {"title": "Content repurposing chain",
             "when": "You have one good piece of content.",
             "prompt": "Here is a blog post: [PASTE]. Repurpose it into: (1) a 10-post social thread with hooks, (2) a 30-second video script, (3) a newsletter teaser (80 words), (4) a LinkedIn post with a contrarian take from the content, (5) 3 quote cards with the strongest lines. Keep the core message identical across all - just change the container.",
             "customize": "Repurpose the winner, not everything.",
             "output": "A week of content from one asset."},
            {"title": "Social caption bank (30 days)",
             "when": "Your calendar is empty.",
             "prompt": "Write 30 social captions for [PLATFORM] for [BUSINESS] targeting [AUDIENCE]. Mix: 10 value (tips/how-to), 8 story (behind the scenes), 6 proof (results/customers), 4 engagement (questions/polls), 2 promo (soft sell). Each under 80 words with 3-5 hashtags. Vary the opening lines - no repeating 'Did you know...'. Keep the brand voice [VOICE].",
             "customize": "Bank them, then post daily and adapt to what lands.",
             "output": "A month of content ready to schedule."},
            {"title": "LinkedIn post from experience",
             "when": "You had a work lesson worth sharing.",
             "prompt": "Turn this experience into a LinkedIn post: [WHAT HAPPENED]. Structure: hook line (the lesson or the twist), 3-5 short paragraphs telling it with one concrete detail each, the takeaway, and a question to invite comments. No 'I'm thrilled to share', no hashtag spam (max 3), no em-dash abuse. 150-250 words.",
             "customize": "The more specific the detail, the more relatable the post.",
             "output": "A LinkedIn post that gets comments from strangers."},
            {"title": "Email newsletter issue",
             "when": "Weekly newsletter time.",
             "prompt": "Write this week's newsletter for [AUDIENCE] around the theme '[THEME]'. Structure: (1) 2-sentence opener with the week's take, (2) the main story/lesson with a real example, (3) 3 quick links/resources with one-line why-they-matter, (4) one question to reply to. 250-350 words. Tone: [TONE] - like a smart friend, not a brand.",
             "customize": "Reply-to questions create your next issue's material.",
             "output": "A newsletter people actually open and answer."},
            {"title": "Video script - short form (Reels/TikTok/Shorts)",
             "when": "Creating a short video.",
             "prompt": "Write a [X]-second video script for [TOPIC] to [AUDIENCE]. Structure by second: 0-3 hook (pattern interrupt), 3-10 the promise, 10-20 the proof or demo, 20-30 the payoff + CTA. Written for voiceover - short sentences, no words you wouldn't say aloud. Add one caption line and one on-screen text suggestion.",
             "customize": "Steal the hook patterns from videos that already blew up in your niche.",
             "output": "A script tight enough to film in one take."},
            {"title": "Content calendar builder",
             "when": "Planning the month.",
             "prompt": "Build a 4-week content calendar for [BUSINESS] across [PLATFORMS]. For each day: format, topic, hook line, CTA, and which pillar it serves (educate/entertain/inspire/promote). Balance: 60% value, 20% story, 10% proof, 10% promo. Leave 2 slots per week flexible for trends. Use these seed topics: [TOPICS].",
             "customize": "Schedule it in your tool and move on - don't overthink.",
             "output": "A calendar that removes 'what do I post' forever."},
            {"title": "Google Business Profile posts",
             "when": "Local SEO + appearing in maps.",
             "prompt": "Write 7 Google Business Profile posts for [LOCAL BUSINESS] this week: 2 offers, 2 updates (new stock/services), 1 event, 1 behind-the-scenes, 1 customer-win. Each under 300 chars (Google's limit), with a CTA and a keyword [LOCAL KEYWORD + CITY]. No hashtags on Google posts.",
             "customize": "Add a photo to every post - posts with photos get 3x engagement.",
             "output": "A week of local visibility in minutes."},
            {"title": "Voice-of-customer mining",
             "when": "You're out of content ideas.",
             "prompt": "Here are comments, DMs and reviews from my audience: [PASTE]. Extract: (1) the 5 most repeated problems, (2) the exact phrases people use to describe them (verbatim - these become headlines), (3) the 3 questions that show up most, (4) 10 content ideas directly answering these, each with a working title. This is a goldmine - treat the phrases as sacred.",
             "customize": "Mine once a month; your audience writes your calendar.",
             "output": "Content ideas that are guaranteed relevant because they're real."},
        ],
    },
    {
        "id": "pkg-smb-01",
        "sku": "PKG-SMB-01",
        "title": "SMB Operator: Marketing, Reviews & Local Growth",
        "desc": "10 prompts for social posts, Google reviews, local ads and customer win-back messages for busy owners.",
        "category": "smb",
        "price": 85,
        "count": 10,
        "intro": "Built for owners with 30 minutes a week, not a marketing team. Every prompt produces something you can post, send or run within minutes.",
        "prompts": [
            {"title": "Google review reply - positive",
             "when": "A happy customer left 4-5 stars.",
             "prompt": "Write a reply to this Google review: '[REVIEW TEXT]' from [CUSTOMER NAME]. Thank them by name, mention one specific detail from their review, invite them back with a small hook ([LOYALTY OFFER - e.g. 10% off next visit]), and keep it under 60 words. Warm, human, no corporate phrases like 'we appreciate your feedback'.",
             "customize": "Reply within 48 hours - speed signals care.",
             "output": "A reply that makes that customer a regular."},
            {"title": "Google review reply - negative",
             "when": "A bad review just dropped.",
             "prompt": "Write a reply to this negative review: '[REVIEW TEXT]'. Rules: (1) apologize for the specific experience without grovelling, (2) state the facts calmly if the review is inaccurate, (3) offer a concrete fix offline (phone/visit), (4) never argue or mention the reviewer's tone. Under 80 words. End with an invitation to give us another chance.",
             "customize": "Send the same fix to your team so it doesn't repeat.",
             "output": "A reply that shows future customers how you handle problems."},
            {"title": "Review request to happy customers",
             "when": "Right after a good transaction.",
             "prompt": "Write a short message asking [CUSTOMER] for a Google review after [WHAT THEY BOUGHT]. Make it easy: (1) one line on why reviews help a small business like ours, (2) a direct link, (3) a one-question prompt: 'What would you tell a friend about us?'. Optionally offer a small thank-you ([INCENTIVE]). Under 60 words, text-message friendly.",
             "customize": "Send it 2 hours after the visit, not 2 weeks.",
             "output": "A steady drip of new reviews without awkwardness."},
            {"title": "Local ad copy (Facebook/Instagram)",
             "when": "Running a local promo.",
             "prompt": "Write 3 local ad variations for [BUSINESS] offering [OFFER] in [CITY/AREA]. Each: 35-word primary text mentioning the location, 2 headlines (one with the offer, one with the result), 1 CTA. Angles: (1) problem they have [PROBLEM], (2) new in the area, (3) limited offer [DEADLINE]. No stock-photo language, no exclamation spam.",
             "customize": "Target radius 5-15 km around your shop.",
             "output": "Local ads that feel like a neighbour recommended you."},
            {"title": "Customer win-back SMS/email",
             "when": "Old customers went quiet.",
             "prompt": "Write a win-back message to customers who haven't visited in 90+ days. We're [BUSINESS] in [AREA]. Structure: (1) we miss you + one specific thing they might remember, (2) what's new since they last came [NEWS], (3) a real incentive [OFFER - e.g. GH₵ 20 off] with an expiry [DATE]. Keep it under 100 words, warm not desperate.",
             "customize": "Segment by what they bought before if your system allows.",
             "output": "A message that brings back the customers you already paid to acquire."},
            {"title": "Weekend social post pack",
             "when": "You need 3 posts, fast.",
             "prompt": "Write 3 social posts for [BUSINESS] this weekend: (1) Saturday - a 'what we've been up to' story post with a behind-the-scenes detail, (2) Sunday - a value post (tip/advice related to what we sell) [TOPIC], (3) a soft promo for [OFFER]. Each under 70 words, with 3 relevant hashtags. Voice: [VOICE].",
             "customize": "Snap one real photo for each - posts with faces win.",
             "output": "A weekend of content in 10 minutes."},
            {"title": "New product/service announcement",
             "when": "Launching something new.",
             "prompt": "Write an announcement for [NEW PRODUCT/SERVICE] at [BUSINESS]: (1) 3 social captions (curiosity, benefit, story angles), (2) an email or WhatsApp broadcast (100 words), (3) a 20-second video script. Each must answer: what it is, who it's for, what it costs, how to get it. No hype words.",
             "customize": "Pre-sell to your regulars before the public announcement.",
             "output": "A launch that hits every channel you actually use."},
            {"title": "Local partnership pitch",
             "when": "Finding businesses to cross-promote with.",
             "prompt": "Write a short pitch to [PARTNER BUSINESS] in [AREA] for a cross-promotion: we serve [OUR AUDIENCE], they serve [THEIR AUDIENCE], and there's overlap. Propose a simple swap: [WHAT WE OFFER THEM] for [WHAT THEY OFFER US - e.g. flyer in their shop, social shoutout, bundle deal]. Keep it under 120 words, specific about the overlap.",
             "customize": "Pick partners whose customers are your customers.",
             "output": "A pitch that builds your growth network for free."},
            {"title": "Seasonal promo ideas",
             "when": "A holiday or season is coming.",
             "prompt": "Give me 5 promotional ideas for [BUSINESS] for [SEASON/HOLIDAY] in [AREA]. For each: the offer, the angle, the channel (social/email/in-store), and a one-line hook. Focus on things a small team can actually execute in a week - no 3-month campaigns.",
             "customize": "Pick ONE idea and execute it well.",
             "output": "A seasonal promo menu to choose from."},
            {"title": "Handling a viral moment",
             "when": "Something about your business went unexpectedly viral.",
             "prompt": "A post about my business [WHAT HAPPENED - e.g. a video, a review, a complaint] is getting traction. Write: (1) a public reply/comment that's gracious and on-brand [VOICE], (2) a follow-up post that turns the attention into something useful (offer, story, clarification), (3) what NOT to say in the comments. Keep everything under 80 words each.",
             "customize": "Reply fast while attention is high; stay humble.",
             "output": "A playbook for turning chaos into customers."},
        ],
    },
    {
        "id": "pkg-cre-01",
        "sku": "PKG-CRE-01",
        "title": "Creator Script System: Hooks & Long-Form",
        "desc": "8 prompts for retention-structured hooks, beat sheets and 8-12 minute scripts with anti-generic constraints.",
        "category": "creators",
        "price": 75,
        "count": 8,
        "intro": "The difference between a video that dies and one that holds is structure, not talent. These prompts enforce the retention structure - you bring the voice.",
        "prompts": [
            {"title": "Hook bank - 10 options",
             "when": "You have a topic but no opening.",
             "prompt": "Write 10 hook options for a video about [TOPIC] for [AUDIENCE]. Use these patterns, 2 each: (1) shocking/contrarian statement, (2) specific number or result, (3) 'everyone's wrong about X' take, (4) open loop/question, (5) personal stake ('I almost gave up on X'). Max 15 words each. Mark the 2 strongest for a 0-3 second cold open. No 'hey guys', no 'in this video'.",
             "customize": "The hook must be true - the video has to deliver it.",
             "output": "10 cold opens to test; the first 3 seconds decide everything."},
            {"title": "Retention beat sheet",
             "when": "Before writing the script.",
             "prompt": "Create a beat sheet for a [X]-minute video on [TOPIC]. Structure: 0:00-0:20 hook + promise, 0:20-1:00 stakes/credibility, then 3-5 main beats each with: the point, the example, the retention device (open loop, payoff tease, pattern interrupt), and approximate timestamps. Add 1 counterpoint beat (address the obvious objection). End: recap + specific next-video tease.",
             "customize": "Place your strongest beat at ~40% in - that's where drop-off peaks.",
             "output": "A roadmap that keeps viewers watching to the end."},
            {"title": "Full script from beat sheet",
             "when": "Beat sheet approved.",
             "prompt": "Write the full script from this beat sheet: [PASTE]. [X] minutes spoken (~[WORD COUNT] words). Rules: (1) write for the ear - short sentences, contractions, words you'd actually say, (2) no stage directions, no headings, (3) no filler transitions, (4) one concrete detail per beat, (5) end on the tease. Tone: [TONE].",
             "customize": "Read it aloud once - if you stumble, rewrite that line.",
             "output": "A script you can record without sounding like you're reading."},
            {"title": "Open loop creation",
             "when": "Script feels flat in the middle.",
             "prompt": "Here's a section of my script: [PASTE]. Rewrite it to include 3 open loops: moments where I promise to answer something later (e.g. 'the reason is weirder than you think - I'll show you in a minute'). Also add 2 callbacks: references to earlier moments that reward attentive viewers. Keep the content identical - just add tension.",
             "customize": "Close every loop you open by the end - unresolved loops lose trust.",
             "output": "A middle section viewers can't leave."},
            {"title": "De-AI pass on script",
             "when": "Draft sounds like ChatGPT wrote it.",
             "prompt": "Rewrite this script to remove every AI tell: [PASTE]. Remove: em-dashes overuse, 'it's not just X, it's Y', 'the truth is', 'in today's world', triple-word repetitions for rhythm, perfectly balanced sentences. Replace with: sentence fragments, rhetorical questions, one inside joke or personal detail per section, and 2 moments of specific self-deprecation. Keep all facts and structure.",
             "customize": "Add one detail only you would know - AI can't invent that.",
             "output": "A script that sounds like you talking to a friend."},
            {"title": "Title + thumbnail pairing",
             "when": "Script done, packaging time.",
             "prompt": "For this video [TOPIC/SCRIPT SUMMARY], generate: (1) 8 titles under 60 chars mixing curiosity, number and contrarian formats, (2) for the top 3 titles, a thumbnail concept: focal subject, expression/emotion, background, text overlay (max 3 words), and why it works, (3) which title-thumbnail pair is strongest and why. Avoid: red arrows, fake shock, text that duplicates the title.",
             "customize": "The title and thumbnail must promise the same thing.",
             "output": "A package that earns the click the script deserves."},
            {"title": "Pattern interrupt mid-script",
             "when": "Viewers drop at a predictable point.",
             "prompt": "Here is my script around the [X] minute mark: [PASTE]. Viewers drop off here. Rewrite this section to include 2 pattern interrupts: a sudden change in pacing (a fast cut beat, a direct question to camera, a surprising sound/visual note), and re-order the section so the most interesting fact comes before the explanation. Keep the information identical.",
             "customize": "Watch your analytics to find the exact drop-off point first.",
             "output": "A section that resets attention exactly where it fades."},
            {"title": "Series concept design",
             "when": "You want a repeatable format.",
             "prompt": "Design a 6-episode video series on [BROAD TOPIC] for [AUDIENCE]. For each episode: working title, the single promise, the hook angle, and how it builds on the previous episode. Plus: the 3-episode rule - which 3 episodes make a complete mini-series if I only make 3, and a naming pattern that makes the series recognizable.",
             "customize": "A series beats one-offs for the algorithm and for you.",
             "output": "A month of content with a built-in audience pull."},
        ],
    },
    {
        "id": "pkg-dev-01",
        "sku": "PKG-DEV-01",
        "title": "AI Pair Programmer: Code, Debug & Review",
        "desc": "10 prompts for generating, debugging and reviewing code with context-stuffing and test-first instructions.",
        "category": "dev",
        "price": 145,
        "count": 10,
        "intro": "AI writes code fast and confidently wrong. These prompts force the context, constraints and verification that turn 'fast' into 'safe'. Always review what it ships - that's the job.",
        "prompts": [
            {"title": "Code generation with full context",
             "when": "Writing a non-trivial function.",
             "prompt": "Act as a senior [LANGUAGE] developer. Write a function to [TASK]. Context: [PASTE: language version, framework, existing function signatures, coding style]. Constraints: (1) handle edge cases [EDGE CASES], (2) no external dependencies beyond [ALLOWED], (3) follow [STYLE GUIDE], (4) include type hints/docstrings. First write 3 test cases with expected outputs, then the implementation, then any assumptions you made.",
             "customize": "Paste real signatures - vague context gives vague code.",
             "output": "Implementation + tests + assumptions you can actually review."},
            {"title": "Debug with error + code",
             "when": "You have a failing stack trace.",
             "prompt": "Here is my code: [PASTE CODE]. Here is the error: [PASTE ERROR/STACK TRACE]. Here's what I expected to happen: [EXPECTED]. Diagnose in this order: (1) root cause in one sentence, (2) why it happens (the mechanism), (3) the fix with minimal changes, (4) a test that would have caught it. If multiple causes are possible, rank them. Do NOT rewrite the whole file.",
             "customize": "Include the line numbers from the trace - it cuts the search space.",
             "output": "A diagnosis you understand, not a mystery patch."},
            {"title": "Code review pass",
             "when": "Before merging.",
             "prompt": "Review this code like a senior engineer doing a merge review: [PASTE CODE]. Report: (1) bugs (with the failing scenario), (2) security issues, (3) performance problems with complexity notes, (4) readability/maintainability, (5) missing tests. For each finding: severity (critical/major/minor), the fix, and whether it blocks merge. Be specific - quote the lines.",
             "customize": "Run it on your own code before you claim it's done.",
             "output": "A review that catches what your rubber duck missed."},
            {"title": "SQL query from schema",
             "when": "Writing a business query.",
             "prompt": "Act as a senior analytics engineer in [DATABASE - e.g. Postgres]. Here are my tables with columns: [PASTE SCHEMA]. Business question: [PASTE QUESTION]. Write the SQL using: named CTEs with comments, no SELECT *, explicit joins, and a final SELECT with no more than 8 columns. List any assumptions about the data. Then give me a quick way to sanity-check the numbers.",
             "customize": "Include row counts if you know them - it changes the approach.",
             "output": "Query + assumptions + a verification step."},
            {"title": "Optimize a slow query",
             "when": "Query runs forever.",
             "prompt": "Here is my query: [PASTE]. It runs in [X] seconds on ~[N] million rows. Find: (1) top 3 bottlenecks with line references, (2) a rewritten version with each optimization annotated, (3) expected improvement per change, (4) index recommendations (exact DDL), (5) a pre-aggregation strategy if it's still slow. Don't change the result set.",
             "customize": "Run EXPLAIN ANALYZE first and paste it - huge signal.",
             "output": "A query plan you can implement and measure."},
            {"title": "Write tests first (TDD)",
             "when": "New feature, discipline required.",
             "prompt": "I'm building [FEATURE] in [LANGUAGE/FRAMEWORK]. Write the test suite FIRST covering: (1) happy path, (2) edge cases [LIST], (3) failure modes (bad input, missing data, timeouts), (4) one performance sanity test if relevant. Use [TEST FRAMEWORK] conventions. I'll write the implementation to pass these tests. No skipping - if a case is impossible, say why.",
             "customize": "TDD with AI works: it turns 'trust me' into 'prove it'.",
             "output": "Tests that define done before a line of implementation."},
            {"title": "Explain a codebase fast",
             "when": "Onboarding into unfamiliar code.",
             "prompt": "Here is the entry point and file tree of an unfamiliar codebase: [PASTE: main file, key files, package manifest]. Explain: (1) what this app does in 3 sentences, (2) the request lifecycle from entry to response, (3) the 5 most important files and why, (4) where the business logic lives vs. plumbing, (5) the most likely places bugs hide. Assume I know [LANGUAGE] but not this codebase.",
             "customize": "Start with the smallest file and grow outward.",
             "output": "A map that turns 'where do I start' into a plan."},
            {"title": "Security review of a snippet",
             "when": "Before shipping anything user-facing.",
             "prompt": "Security review this code: [PASTE]. Check specifically for: injection (SQL/command/HTML), broken auth or authorization, unsafe deserialization, secret leakage, path traversal, rate-limit gaps, and dependency red flags. For each finding: severity, exploit scenario in one sentence, and the fix. Assume worst-case user input reaches this code.",
             "customize": "Run this on your auth and payment code first.",
             "output": "A security pass that finds holes before users do."},
            {"title": "Refactor without changing behavior",
             "when": "Code works but is hard to read.",
             "prompt": "Refactor this code for readability without changing behavior: [PASTE CODE]. Goals: (1) smaller functions with clear names, (2) remove duplication, (3) early returns over nested conditionals, (4) keep the public interface identical. Show a diff-style before/after for each change and note any place where behavior could accidentally change so I can test it.",
             "customize": "Run your tests before and after - behavior is sacred.",
             "output": "Cleaner code with the blast radius mapped."},
            {"title": "Deployment checklist for a release",
             "when": "About to ship.",
             "prompt": "I'm about to deploy [FEATURE/CHANGE] to [ENV - staging/prod]. Here's what changed: [SUMMARY + DIFF HIGHLIGHTS]. Build a deployment checklist: (1) pre-deploy checks (migrations, config, backups), (2) the deploy steps in order, (3) post-deploy verification (what to check in logs/metrics), (4) rollback plan with the exact revert steps, (5) a 'canary' smoke test script if applicable. Keep it executable, not theoretical.",
             "customize": "The rollback plan matters more than the deploy steps.",
             "output": "A checklist that makes releases boring again."},
        ],
    },
]

EXTRA_PACKS = [
    {
        "id": "pkg-mkt-03",
        "sku": "PKG-MKT-03",
        "title": "Complete Copy & Content System",
        "desc": "The full 12-prompt marketing system: positioning, campaigns, copy, content, repurposing and performance review.",
        "category": "marketing",
        "price": 165,
        "count": 12,
        "intro": "The whole marketing engine in one pack. Run these prompts in order when building a campaign, then weekly to keep it running.",
        "prompts": [
            {"title": "Positioning statement", "when": "Before any campaign.",
             "prompt": "Build a positioning statement for [PRODUCT/SERVICE]. Audience: [AUDIENCE]. Category: [CATEGORY]. Key benefit: [BENEFIT]. Key difference vs [COMPETITORS]: [DIFFERENCE]. Output: one sentence following 'For [AUDIENCE] who [PAIN], [PRODUCT] is the [CATEGORY] that [BENEFIT], unlike [ALTERNATIVE] because [DIFFERENCE]'.",
             "customize": "Test it on a customer — if they nod, it's right.",
             "output": "The one sentence every ad should be able to trace back to."},
            {"title": "Campaign brief", "when": "Kicking off a campaign.",
             "prompt": "Write a one-page campaign brief for [OFFER]: objective (awareness/traffic/sales), audience with 3 pains, core message, proof points, channels [LIST], budget GH₵ [AMOUNT], timeline [WEEKS], success metric, and 3 creative angles. Keep it skimmable - an agency could execute it without asking questions.",
             "customize": "Pick ONE primary metric - a brief with 3 goals has none.",
             "output": "A brief that keeps every channel marching in the same direction."},
            {"title": "Channel-by-channel message map", "when": "Same campaign, many channels.",
             "prompt": "For the campaign [BRIEF SUMMARY], write the adapted message for: email (150 words), Instagram/Facebook post (70 words), LinkedIn post (200 words), landing page hero (30 words), WhatsApp broadcast (50 words). Same core promise, different containers. Note the channel-specific tweak for each.",
             "customize": "Match the platform's natural voice - LinkedIn is formal, WhatsApp is chatty.",
             "output": "A message map that keeps one campaign consistent everywhere."},
            {"title": "Repurposing engine", "when": "One asset, zero time.",
             "prompt": "Take this content: [PASTE]. Repurpose into: 5 social posts, 3 email sections, 1 short video script (30s), 1 long-form blog outline, 3 quote cards, and 1 infographic outline. Keep the core message identical. Rank the repurposed pieces by expected reach.",
             "customize": "Start with your best-performing asset, not your newest.",
             "output": "Six weeks of content from one piece of work."},
            {"title": "Content pillar map", "when": "Planning a quarter.",
             "prompt": "Design 4 content pillars for [BRAND] in [NICHE]: pillar name, audience question it answers, 3 formats that fit it, and 2 examples of existing content that worked. Then generate 12 content ideas (3 per pillar) with working titles.",
             "customize": "Pillars should overlap with what you can prove you know.",
             "output": "A quarter of content with a reason behind every piece."},
            {"title": "Competitor gap analysis", "when": "Feeling outmatched.",
             "prompt": "Here are 3 competitors and their content: [PASTE LINKS/NOTES]. Compare: what they cover, their tone, their offers, what they NEVER talk about. Identify: (1) the topic gap we can own, (2) the tone gap (e.g. they're corporate, we can be plain), (3) the offer gap, (4) 5 content ideas exploiting the gaps.",
             "customize": "Gaps you can exploit are more valuable than strengths you can copy.",
             "output": "A map of the territory they've left open for you."},
            {"title": "Sales page structure", "when": "Building a high-converting page.",
             "prompt": "Outline a sales page for [OFFER] at GH₵ [PRICE] using this structure: (1) hero - outcome + proof, (2) problem agitation, (3) solution + how it works, (4) features as benefits, (5) social proof, (6) objection handling, (7) offer stack + guarantee, (8) scarcity/deadline, (9) FAQ, (10) final CTA. Write the headline + first paragraph for each section.",
             "customize": "Move objection handling before pricing if your audience is skeptical.",
             "output": "A page skeleton that follows proven conversion anatomy."},
            {"title": "Performance review of a campaign", "when": "Campaign ended.",
             "prompt": "Here are my campaign results: [PASTE METRICS - impressions, clicks, conversions, cost, revenue per channel]. Analyze: (1) what actually drove results vs noise, (2) which channel/angle to double down on, (3) what to kill, (4) 3 hypotheses to test next time, (5) a one-paragraph summary for my boss/client.",
             "customize": "Include the creative variants so the 'why' is visible.",
             "output": "A review that turns spend into learning."},
            {"title": "Newsletter welcome sequence", "when": "New subscribers.",
             "prompt": "Write a 4-email welcome sequence for new subscribers to [BRAND]: email 1 - the welcome + what to expect + best resource, email 2 - the story (why we exist), email 3 - the proof (best results), email 4 - the first offer (soft). Each 100-150 words, ending with one action. No 'I'm thrilled to have you' cliches.",
             "customize": "Email 2's story should be true and specific.",
             "output": "A welcome path that turns subscribers into buyers."},
            {"title": "Launch day plan", "when": "Launch week.",
             "prompt": "Build a 7-day launch plan for [OFFER]: day-by-day activities across email/social/WhatsApp/partners, each with the asset needed and the expected action. Include: pre-launch tease (day -3 to -1), launch day burst, mid-launch proof drop, final-day urgency. Mark the 3 highest-impact actions.",
             "customize": "Fewer channels done daily beats many channels done once.",
             "output": "A launch calendar with no dead days."},
            {"title": "UGC/testimonial mining", "when": "No proof to show.",
             "prompt": "Here are customer messages/reviews: [PASTE]. Extract: (1) the 5 strongest quotes verbatim, (2) for each, the result mentioned and the emotion, (3) which quote fits which use case (ads, landing page, email), (4) a request template to ask for permission to use each.",
             "customize": "Get written permission - screenshots without it are risky.",
             "output": "A proof library from customers who already did the selling."},
            {"title": "Monthly marketing report", "when": "Reporting time.",
             "prompt": "Turn these numbers into a monthly report: [PASTE METRICS]. Structure: (1) headline - the one number that matters, (2) what worked with evidence, (3) what didn't with reasons, (4) spend vs return, (5) next month's plan with 3 priorities. Under 300 words, plain language, a non-marketer could understand it.",
             "customize": "Lead with the number your boss cares about, not the one you like.",
             "output": "A report that makes your work legible to anyone."},
        ],
    },
    {
        "id": "pkg-cre-02",
        "sku": "PKG-CRE-02",
        "title": "Creator Script System: Shorts, Titles & Thumbnails",
        "desc": "10 prompts for Shorts scripts, CTR titles, thumbnail concepts and packaging that stops the scroll.",
        "category": "creators",
        "price": 85,
        "count": 10,
        "intro": "The packaging half of the Creator Script System. If your content is good but no one clicks, this pack fixes the click.",
        "prompts": [
            {"title": "Shorts script - 30 seconds", "when": "Vertical video.",
             "prompt": "Write a 30-second Shorts script on [TOPIC] for [AUDIENCE]. Beat structure: 0-3s hook (question or claim), 3-10s the promise, 10-22s two quick points with examples, 22-30s payoff + follow CTA. Spoken-word style, short sentences. Add a caption line and on-screen text suggestion per beat.",
             "customize": "One idea only - Shorts that cover two ideas lose both.",
             "output": "A script tight enough to film in one take."},
            {"title": "Title CTR bank", "when": "Choosing a title.",
             "prompt": "Write 12 title options for a video about [TOPIC] using these formats, 3 each: number/list ('7 signs…'), curiosity gap ('the reason nobody tells you…'), contrarian ('stop doing X'), and result ('how I…'). Under 60 characters each. For the top 3, say which viewer emotion each targets.",
             "customize": "Check your niche's top videos - borrow formats, never titles.",
             "output": "A title bank you can A/B on the same video."},
            {"title": "Thumbnail concept generator", "when": "Before designing.",
             "prompt": "Generate 8 thumbnail concepts for the video '[TITLE]'. For each: focal subject, facial expression/emotion, background, text overlay (max 3 words), composition note, and why it would earn the click. Avoid cliches: red arrows, shocked-face cliches, text that duplicates the title.",
             "customize": "The thumbnail must promise what the title promised.",
             "output": "A thumbnail shortlist that survives the small-screen test."},
            {"title": "First 5 seconds rewrite", "when": "Retention dies instantly.",
             "prompt": "Here is my current opening: [PASTE]. Rewrite the first 5 seconds (20 words max) as: (1) a pattern interrupt (unexpected statement), (2) a specific number, (3) a direct question to the viewer. Keep the promise identical. Then write the first sentence that must follow each hook.",
             "customize": "Record 3 versions and pick by feel - delivery matters as much as words.",
             "output": "Cold opens that stop the scroll before the scroll stops you."},
            {"title": "End screen CTA + next video tease", "when": "Finishing a script.",
             "prompt": "Write the last 15 seconds of this video: [SCRIPT SUMMARY]. Include: (1) a recap line of the one takeaway, (2) a tease of the next video [NEXT TOPIC] that creates an open loop, (3) a subscribe line with a specific reason ('I post every Tuesday about X'), (4) a comment question. 40-60 words total.",
             "customize": "The tease should make the next video feel like a debt you owe them.",
             "output": "An ending that feeds the algorithm and the series."},
            {"title": "Description + tags pack", "when": "Upload day.",
             "prompt": "Write the upload metadata for a video titled '[TITLE]' about [TOPIC]: (1) a 150-word description with the hook repeated, 3 bullet takeaways, and a CTA, (2) 15 SEO tags mixing broad and specific, (3) 3 chapters with timestamps if the video has sections, (4) a pinned comment with a question.",
             "customize": "Put your target keyword in the first 100 characters.",
             "output": "Metadata that gives the algorithm and the viewer what they want."},
            {"title": "Comment section engine", "when": "Boosting engagement after posting.",
             "prompt": "Here is my video [TOPIC]. Write: (1) 10 comment replies I can post to early viewers that add value or ask questions, (2) 5 comment prompts I can post myself (a hot take, a question, a correction) to spark threads, (3) the 3 comment types I should reply to first.",
             "customize": "Reply within the first hour - early engagement compounds.",
             "output": "A comment strategy that turns viewers into commenters."},
            {"title": "Series hook across episodes", "when": "Starting a series.",
             "prompt": "For a series on [TOPIC], write: (1) a 5-second series intro hook (same across episodes, one line), (2) the pattern each episode follows (open loop from last time, new lesson, tease next), (3) 5 episode titles that make the series feel like a progression, (4) a one-line series pitch for new viewers.",
             "customize": "Series with a pattern build a habit; habits build subscribers.",
             "output": "A series format viewers learn to expect."},
            {"title": "Trend adaptation", "when": "A trend is blowing up in your niche.",
             "prompt": "The trend '[TREND]' is big for [AUDIENCE]. Adapt it to [MY CHANNEL TOPIC] without copying: (1) 3 angles that fit my channel's promise, (2) for each - the hook, the twist that makes it mine, the CTA, (3) how to post within 48 hours while the trend peaks. Flag anything that would feel off-brand.",
             "customize": "Trends serve the channel, never the other way around.",
             "output": "A trend play that borrows attention, not content."},
            {"title": "Analytics review for creators", "when": "Monthly check-in.",
             "prompt": "Here are my channel stats: [PASTE - views, retention, CTR, subs]. Analyze: (1) the pattern in my top 3 videos vs bottom 3 (titles? topics? length?), (2) my average retention curve's biggest drop point, (3) 3 specific changes for next month, (4) one thing to stop doing. Be blunt.",
             "customize": "Compare like-for-like: same topic, different packaging tells you what packaging does.",
             "output": "A monthly review that turns data into one clear change."},
        ],
    },
    {
        "id": "pkg-cre-03",
        "sku": "PKG-CRE-03",
        "title": "Creator Complete System",
        "desc": "The full 12-prompt system: ideas, research, scripts, packaging, repurposing and analytics.",
        "category": "creators",
        "price": 155,
        "count": 12,
        "intro": "The complete creator workflow: find ideas, research them, script them, package them, ship them, and learn from them. Combines the hooks system and the packaging system into one pipeline.",
        "prompts": [
            {"title": "Idea mining from your niche", "when": "Out of ideas.",
             "prompt": "Mine 15 video ideas for [NICHE] targeting [AUDIENCE] from: (1) the top 20 videos in the niche (what angles repeat, what's missing), (2) questions people ask in comments, (3) my own expertise [MY SKILLS]. Label each idea: evergreen or trending, and the hook angle. No 'reacts' or 'top 10' filler unless it fits the channel.",
             "customize": "The missing angles are your best opportunities.",
             "output": "A month of ideas with reasons behind each."},
            {"title": "Keyword research for creators", "when": "Choosing between topics.",
             "prompt": "For the topic '[TOPIC]', research the angle space: (1) 8 search phrases people use (long-tail), (2) which existing videos rank and what they cover, (3) 3 angles not covered, (4) a recommendation: which angle I should make first and why. Act as a YouTube strategist.",
             "customize": "Search yourself - the 'people also ask' box is free research.",
             "output": "A topic decision backed by evidence, not gut feel."},
            {"title": "Viewer avatar", "when": "Before a content sprint.",
             "prompt": "Build a viewer avatar for [CHANNEL NICHE]: demographics, what they watch before bed, their level of knowledge, their 3 biggest frustrations, the words they search, what makes them click vs scroll, what makes them subscribe vs just watch. Then write 3 content briefs this avatar would click.",
             "customize": "Steal details from real comments on your videos.",
             "output": "A target so clear that 'who is this for?' stops being a question."},
            {"title": "Content sprint plan", "when": "Batch production day.",
             "prompt": "Plan a 1-day content sprint producing [N] videos: (1) the batch order (research -> scripts -> packaging), (2) for each video - topic, hook, title, thumbnail concept, (3) what to prepare in advance (b-roll, props), (4) timebox per step so the day finishes. Realistic for a solo creator.",
             "customize": "Batching packaging with scripting keeps the promise consistent.",
             "output": "A sprint board that makes a day produce a month."},
            {"title": "Script from research notes", "when": "Raw material in hand.",
             "prompt": "Here are my research notes: [PASTE - links, stats, quotes, examples]. Write a [X]-minute script that: opens with the strongest hook from the notes, structures the points in a rising order of interest, cites the stat with its source naturally ('a 2025 study found…'), ends with a takeaway and next-video tease. No filler.",
             "customize": "The strongest point goes at 40% in, not the end.",
             "output": "A script built from real material, not AI averages."},
            {"title": "Repurpose a long video into Shorts", "when": "Long content underperforming.",
             "prompt": "From this long-form script: [PASTE], extract 5 Shorts: each with (1) the 30-second cut (which beat to use), (2) a new hook for standalone viewing, (3) the caption, (4) which part of the long video it links back to. Different beats - no duplicates.",
             "customize": "Shorts that tease the long video can feed it views.",
             "output": "Five vertical videos from one horizontal one."},
            {"title": "Collaboration pitch", "when": "Finding collab partners.",
             "prompt": "Write a collab pitch to [CREATOR] (subs: [N]) from me ([MY CHANNEL], [MY SUBS], [MY NICHE]). Proposed video: [IDEA] that plays to both audiences. Explain in 3 sentences why it works for THEM (their audience gets X), what I bring, and the simple next step. Under 120 words, no flattery spam.",
             "customize": "Reference one of their actual videos - it doubles reply rates.",
             "output": "A pitch that feels like an opportunity, not a request."},
            {"title": "Monetization plan", "when": "Ready to earn.",
             "prompt": "Build a monetization plan for [CHANNEL] with [N] subs in [NICHE]. Compare: AdSense, sponsorships, digital products (prompts/ebooks/courses), memberships, affiliate. For each: requirements, realistic monthly range at my size, effort, and fit with my audience. Recommend a 3-stream combo and the order to add them.",
             "customize": "Digital products beat ads for niche audiences - the math is brutal.",
             "output": "A revenue plan that matches where you are, not where gurus are."},
            {"title": "Comment-to-content loop", "when": "Engagement plateau.",
             "prompt": "Here are 30 comments from my recent videos: [PASTE]. Identify: (1) the 3 most common questions (these become videos), (2) objections or misconceptions worth addressing head-on, (3) compliments that reveal what viewers value most, (4) 5 video titles directly answering the questions.",
             "customize": "Your comment section is a free focus group - run it weekly.",
             "output": "A content loop that lets the audience write your calendar."},
            {"title": "Launch a mini-product to your audience", "when": "Audience ready to buy.",
             "prompt": "Design a mini digital product for [AUDIENCE] based on [TOPIC I'M KNOWN FOR]: (1) the product (prompt pack/guide/template), (2) price in GH₵, (3) the 3 promised outcomes, (4) a 5-day launch plan across my existing content, (5) the CTA script for the launch video.",
             "customize": "Start smaller than feels comfortable - a $7 win beats a $50 maybe.",
             "output": "A product + launch plan that fits a solo creator's bandwidth."},
            {"title": "Weekly creator review", "when": "Every Sunday.",
             "prompt": "Here is my week: [PASTE - videos published, stats, comments, time spent]. Review: (1) what moved and why, (2) the best use of next week's time (content? packaging? community?), (3) one experiment to run next week, (4) what to stop doing. Keep it 5 bullets max.",
             "customize": "Consistency of review matters more than brilliance of review.",
             "output": "A Sunday ritual that compounds weekly."},
        ],
    },
]
